/**
 * Deterministic mock data for the Applicant Grades feature.
 *
 * The seed rows mirror the design canvas (so the demo screens render the
 * exact same names / numbers visible in the prototype). The shape matches
 * `GradeRow` and feeds the in-memory mutable store in `grades.service.ts`.
 */

import type { GradeRow } from './types';

export const SEED_ROWS: GradeRow[] = [
  {
    seat: 142_018,
    seatingNumber: '142018',
    nid: '30412180103456',
    name: 'أحمد محمد إبراهيم سعد',
    kind: 'general',
    gender: 'male',
    branch: 'علمي علوم',
    graduationYear: 2026,
    schoolCategoryCode: 'SCH-A1',
    school: 'ثانوية النيل النموذجية',
    region: 'القاهرة',
    total: 392,
    importMax: 410,
    overrideMax: null,
    lastEditedAt: null,
    lastEditedBy: null,
    status: 'مستجد',
    log: [
      {
        id: 'a1',
        reason: 'SPORTS_ACTIVITY',
        reasonLabel: 'نشاط رياضي',
        note: 'بطولة جمهورية كرة القدم — مركز ثاني · شهادة #ش-2389',
        amount: 10,
        by: 'نهى عبد الفتاح',
        when: '٨ مايو ٢٠٢٦ · ١٠:٢٤ ص',
        isActive: true,
      },
    ],
  },
  {
    seat: 142_119,
    seatingNumber: '142119',
    nid: '30406240178923',
    name: 'محمود السيد عبد الرحمن',
    kind: 'general',
    gender: 'male',
    branch: 'علمي رياضة',
    graduationYear: 2025,
    schoolCategoryCode: 'SCH-A2',
    school: 'ثانوية كفر الدوار',
    region: 'البحيرة',
    total: 367,
    importMax: 410,
    overrideMax: 400,
    lastEditedAt: '١٠ مايو ٢٠٢٦ · ٠٢:١٨ م',
    lastEditedBy: 'مرتضى محمود',
    status: 'مستجد',
    log: [],
  },
  {
    seat: 27_488,
    seatingNumber: '27488',
    nid: '30502110145678',
    name: 'يوسف خالد فؤاد المنياوي',
    kind: 'azhar',
    gender: 'male',
    branch: 'علمي',
    graduationYear: 2026,
    schoolCategoryCode: 'SCH-A6',
    school: 'معهد المنيا الأزهري',
    region: 'المنيا',
    total: 478,
    importMax: 510,
    overrideMax: null,
    lastEditedAt: null,
    lastEditedBy: null,
    status: '—',
    log: [
      {
        id: 'a4',
        reason: 'GRIEVANCE',
        reasonLabel: 'تظلم',
        note: 'إعادة رصد مادة الأحياء — تأكد من خصم 8 درجات.',
        amount: -8,
        by: 'مرتضى محمود',
        when: '١٠ مايو ٢٠٢٦ · ٠٣:٤٠ م',
        isActive: true,
      },
    ],
  },
  {
    seat: 142_204,
    seatingNumber: '142204',
    nid: '30410050189012',
    name: 'عبد الله أحمد ناصر',
    kind: 'general',
    gender: 'male',
    branch: 'علمي علوم',
    graduationYear: 2024,
    schoolCategoryCode: 'SCH-A3',
    school: 'ثانوية الزقازيق الثانية',
    region: 'الشرقية',
    total: 401,
    importMax: 410,
    overrideMax: null,
    lastEditedAt: null,
    lastEditedBy: null,
    status: 'باقٍ للإعادة',
    log: [],
  },
  {
    seat: 27_512,
    seatingNumber: '27512',
    nid: '30501120167845',
    name: 'حسن محمد رمضان السباعي',
    kind: 'azhar',
    gender: 'male',
    branch: 'أدبي',
    graduationYear: 2026,
    schoolCategoryCode: 'SCH-A6',
    school: 'معهد طنطا الأزهري',
    region: 'الغربية',
    total: 442,
    importMax: 510,
    overrideMax: 500,
    lastEditedAt: '٧ مايو ٢٠٢٦',
    lastEditedBy: 'نهى عبد الفتاح',
    status: '—',
    log: [
      {
        id: 'a5',
        reason: 'SPORTS_ACTIVITY',
        reasonLabel: 'نشاط رياضي',
        note: 'بطولة المنطقة لألعاب القوى — مركز أول.',
        amount: 5,
        by: 'نهى عبد الفتاح',
        when: '٦ مايو ٢٠٢٦',
        isActive: true,
      },
    ],
  },
  {
    seat: 142_077,
    seatingNumber: '142077',
    nid: '30407300134567',
    name: 'كريم مصطفى عبد المنعم',
    kind: 'general',
    gender: 'male',
    branch: 'علمي علوم',
    graduationYear: 2026,
    schoolCategoryCode: 'SCH-A4',
    school: 'ثانوية مدينة نصر بنين',
    region: 'القاهرة',
    total: 384,
    importMax: 410,
    overrideMax: null,
    lastEditedAt: null,
    lastEditedBy: null,
    status: 'مستجد',
    log: [],
  },
  {
    seat: 142_322,
    seatingNumber: '142322',
    nid: '30408190156789',
    name: 'إسلام طارق فتحي حلمي',
    kind: 'general',
    gender: 'male',
    branch: 'علمي رياضة',
    graduationYear: 2026,
    schoolCategoryCode: 'SCH-A5',
    school: 'ثانوية الإسكندرية النموذجية',
    region: 'الإسكندرية',
    total: 358,
    importMax: 410,
    overrideMax: null,
    lastEditedAt: null,
    lastEditedBy: null,
    status: 'مستجد',
    log: [],
  },
  {
    seat: 27_603,
    seatingNumber: '27603',
    nid: '30503150123456',
    name: 'مصطفى عمرو عبد الفتاح',
    kind: 'azhar',
    gender: 'male',
    branch: 'علمي',
    graduationYear: 2025,
    schoolCategoryCode: 'SCH-A6',
    school: 'معهد أسيوط الأزهري بنين',
    region: 'أسيوط',
    total: 461,
    importMax: 510,
    overrideMax: null,
    lastEditedAt: null,
    lastEditedBy: null,
    status: '—',
    log: [],
  },
  {
    seat: 142_490,
    seatingNumber: '142490',
    nid: '30411240167890',
    name: 'زياد وائل صبري الجندي',
    kind: 'general',
    gender: 'male',
    branch: 'علمي علوم',
    graduationYear: 2026,
    schoolCategoryCode: 'SCH-A1',
    school: 'ثانوية المنصورة بنين',
    region: 'الدقهلية',
    total: 376,
    importMax: 410,
    overrideMax: null,
    lastEditedAt: null,
    lastEditedBy: null,
    status: 'مستجد',
    log: [
      {
        id: 'a6',
        reason: 'SPORTS_ACTIVITY',
        reasonLabel: 'نشاط رياضي',
        note: 'بطولة محافظات الشمال — كرة سلة.',
        amount: 12,
        by: 'مرتضى محمود',
        when: '٤ مايو ٢٠٢٦',
        isActive: true,
      },
    ],
  },
];

/** Sample duplicates used by the import wizard's mock stage step. */
export const SAMPLE_DUPLICATES = [
  {
    nationalId: '30412180103456',
    name: 'أحمد محمد إبراهيم سعد',
    kind: 'general' as const,
    seatExisting: 142_018,
    seatIncoming: 142_018,
    maxDegree: 410,
    hasChanges: true,
    changedFields: ['total', 'branch'] as const,
    existing: { total: 392, branch: 'علمي علوم', school: 'ثانوية النيل النموذجية', region: 'القاهرة', status: 'مستجد' },
    incoming: { total: 405, branch: 'علمي رياضة', school: 'ثانوية النيل النموذجية', region: 'القاهرة', status: 'مستجد' },
    adjustmentSum: 10,
    adjustmentCount: 1,
  },
  {
    nationalId: '30406240178923',
    name: 'محمود السيد عبد الرحمن',
    kind: 'general' as const,
    seatExisting: 142_119,
    seatIncoming: 142_119,
    maxDegree: 410,
    hasChanges: false,
    changedFields: [] as const,
    existing: { total: 367, branch: 'علمي رياضة', school: 'ثانوية كفر الدوار', region: 'البحيرة', status: 'مستجد' },
    incoming: { total: 367, branch: 'علمي رياضة', school: 'ثانوية كفر الدوار', region: 'البحيرة', status: 'مستجد' },
    adjustmentSum: 0,
    adjustmentCount: 0,
  },
  {
    nationalId: '30502110145678',
    name: 'يوسف خالد فؤاد المنياوي',
    kind: 'azhar' as const,
    seatExisting: 27_488,
    seatIncoming: 27_488,
    maxDegree: 510,
    hasChanges: true,
    changedFields: ['status'] as const,
    existing: { total: 478, branch: 'علمي', school: 'معهد المنيا الأزهري', region: 'المنيا', status: 'مستجد' },
    incoming: { total: 478, branch: 'علمي', school: 'معهد المنيا الأزهري', region: 'المنيا', status: 'باقٍ للإعادة' },
    adjustmentSum: -8,
    adjustmentCount: 1,
  },
  {
    nationalId: '30410050189012',
    name: 'عبد الله أحمد ناصر',
    kind: 'general' as const,
    seatExisting: 142_204,
    seatIncoming: 142_205,
    maxDegree: 410,
    hasChanges: true,
    changedFields: ['total', 'seat', 'status'] as const,
    existing: { total: 401, branch: 'علمي علوم', school: 'ثانوية الزقازيق الثانية', region: 'الشرقية', status: 'باقٍ للإعادة' },
    incoming: { total: 388, branch: 'علمي علوم', school: 'ثانوية الزقازيق الثانية', region: 'الشرقية', status: 'مستجد' },
    adjustmentSum: 0,
    adjustmentCount: 0,
  },
  {
    nationalId: '30407300134567',
    name: 'كريم مصطفى عبد المنعم',
    kind: 'general' as const,
    seatExisting: 142_077,
    seatIncoming: 142_077,
    maxDegree: 410,
    hasChanges: false,
    changedFields: [] as const,
    existing: { total: 384, branch: 'علمي علوم', school: 'ثانوية مدينة نصر بنين', region: 'القاهرة', status: 'مستجد' },
    incoming: { total: 384, branch: 'علمي علوم', school: 'ثانوية مدينة نصر بنين', region: 'القاهرة', status: 'مستجد' },
    adjustmentSum: 0,
    adjustmentCount: 0,
  },
];
