// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PACademy.Modules.Committees.Infrastructure.Persistence;

#nullable disable

namespace PACademy.Modules.Committees.Infrastructure.Migrations
{
    [DbContext(typeof(CommitteesDbContext))]
    partial class CommitteesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChairUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DailyCapacity")
                        .HasColumnType("int");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_committees_status");

                    b.HasIndex("CycleId", "Key")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("committees", (string)null);
                });

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.CommitteeDateBinding", b =>
                {
                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BoundDate")
                        .HasColumnType("date");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CommitteeId", "BoundDate");

                    b.ToTable("committee_date_bindings", (string)null);
                });

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.CommitteeMember", b =>
                {
                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CommitteeId", "UserId");

                    b.ToTable("committee_members", (string)null);
                });

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.CommitteeSpecialization", b =>
                {
                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpecializationKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("CommitteeId", "SpecializationKey");

                    b.ToTable("committee_specializations", (string)null);
                });

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.CommitteeDateBinding", b =>
                {
                    b.HasOne("PACademy.Modules.Committees.Domain.Committee", null)
                        .WithMany("DateBindings")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.CommitteeMember", b =>
                {
                    b.HasOne("PACademy.Modules.Committees.Domain.Committee", null)
                        .WithMany("Members")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.CommitteeSpecialization", b =>
                {
                    b.HasOne("PACademy.Modules.Committees.Domain.Committee", null)
                        .WithMany("Specializations")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Modules.Committees.Domain.Committee", b =>
                {
                    b.Navigation("DateBindings");

                    b.Navigation("Members");

                    b.Navigation("Specializations");
                });
#pragma warning restore 612, 618
        }
    }
}
