// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PACademy.Modules.Lookups.Infrastructure.Persistence;

#nullable disable

namespace PACademy.Modules.Lookups.Infrastructure.Migrations
{
    [DbContext(typeof(LookupsDbContext))]
    [Migration("20260516091657_010b_AddMissingLookupTypes")]
    partial class _010b_AddMissingLookupTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.CategoryCommittee", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("CategoryId", "TargetId")
                        .HasName("PK_CategoryCommittees");

                    b.HasIndex("TargetId");

                    b.ToTable("category_committees", null, t =>
                        {
                            t.HasTrigger("tr_CategoryCommittees_ValidateRefs");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.CategorySpecialization", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("CategoryId", "TargetId")
                        .HasName("PK_CategorySpecializations");

                    b.HasIndex("TargetId");

                    b.ToTable("category_specializations", null, t =>
                        {
                            t.HasTrigger("tr_CategorySpecializations_ValidateRefs");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.CategoryTest", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("CategoryId", "TargetId")
                        .HasName("PK_CategoryTests");

                    b.HasIndex("TargetId");

                    b.ToTable("category_tests", null, t =>
                        {
                            t.HasTrigger("tr_CategoryTests_ValidateRefs");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.LookupItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("delete_reason");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExtrasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extras");

                    b.Property<string>("FacultyCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("faculty_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LookupTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("lookup_type_code");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_en");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("LookupTypeCode", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LookupItem_TypeCode_Code")
                        .HasFilter("[deleted_at] IS NULL");

                    b.HasIndex("ParentId", "DeletedAt")
                        .HasDatabaseName("IX_LookupItem_Parent");

                    b.HasIndex("LookupTypeCode", "IsActive", "DeletedAt")
                        .HasDatabaseName("IX_LookupItem_Type_Active");

                    b.HasIndex("LookupTypeCode", "SortOrder", "CreatedAt")
                        .HasDatabaseName("IX_LookupItem_SortOrder");

                    b.ToTable("lookup_items", null, t =>
                        {
                            t.HasTrigger("tr_LookupItem_BlockDelete");

                            t.HasTrigger("tr_LookupItem_FacultyFK");

                            t.HasTrigger("tr_LookupItem_NoCycles");

                            t.HasCheckConstraint("CK_LookupItem_DateRange", "[start_date] IS NULL OR [end_date] IS NULL OR [start_date] <= [end_date]");

                            t.HasCheckConstraint("CK_LookupItem_NotSelfParent", "[parent_id] IS NULL OR [parent_id] <> [id]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.LookupItemType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CodePrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("HasDates")
                        .HasColumnType("bit");

                    b.Property<bool>("HasExtras")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdminUi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHierarchical")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Padding")
                        .HasColumnType("tinyint");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<short>("SortInSection")
                        .HasColumnType("smallint");

                    b.HasKey("Code");

                    b.HasIndex("CodePrefix")
                        .IsUnique()
                        .HasDatabaseName("UX_LookupItemType_CodePrefix");

                    b.ToTable("lookup_item_types", (string)null);
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.PeriodCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("CategoryId", "TargetId")
                        .HasName("PK_PeriodCategories");

                    b.HasIndex("TargetId");

                    b.ToTable("period_categories", null, t =>
                        {
                            t.HasTrigger("tr_PeriodCategories_ValidateRefs");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.CategoryCommittee", b =>
                {
                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.CategorySpecialization", b =>
                {
                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.CategoryTest", b =>
                {
                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.LookupItem", b =>
                {
                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItemType", null)
                        .WithMany()
                        .HasForeignKey("LookupTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PACademy.Modules.Lookups.Domain.PeriodCategory", b =>
                {
                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PACademy.Modules.Lookups.Domain.LookupItem", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
