-- Auto-generated by frontend/scripts/build-lookup-seed-sql.mts
-- DO NOT edit by hand. Re-run the generator after editing
-- frontend/src/features/lookups/mock/lookups.mock.ts.
--
-- Idempotent — uses MERGE keyed on (lookup_type_code, code). Row IDs are
-- derived deterministically (SHA-1 of 'TYPE:code') so re-runs match.
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRAN;

-- RELATIONSHIPS (34 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('25186047-e5d7-6156-a5d1-199c242e4bd2', N'RELATIONSHIPS', N'REL-001', N'أب', NULL, 1, 0, NULL, NULL, NULL, N'{"branch":"paternal","gender":"male","degree":1}', NULL),
    ('f9c1d16b-98d1-5596-fe6d-8df1bc6e7569', N'RELATIONSHIPS', N'REL-002', N'أم', NULL, 1, 1, NULL, NULL, NULL, N'{"branch":"maternal","gender":"female","degree":1}', NULL),
    ('9fb2733b-ee98-de24-67e2-c18093efa149', N'RELATIONSHIPS', N'REL-003', N'أخ', NULL, 1, 2, NULL, NULL, NULL, N'{"branch":"self","gender":"male","degree":1}', NULL),
    ('a019dfa8-4620-21dd-4c65-0ae7d0d55b12', N'RELATIONSHIPS', N'REL-004', N'أخت', NULL, 1, 3, NULL, NULL, NULL, N'{"branch":"self","gender":"female","degree":1}', NULL),
    ('fae490cc-5e36-ebcd-b82f-3251c29ceb2d', N'RELATIONSHIPS', N'REL-005', N'زوج', NULL, 1, 4, NULL, NULL, NULL, N'{"branch":"spouse","gender":"male","degree":1}', NULL),
    ('9f5c2783-a06b-243b-c95d-109a150b7ef5', N'RELATIONSHIPS', N'REL-006', N'زوجة', NULL, 1, 5, NULL, NULL, NULL, N'{"branch":"spouse","gender":"female","degree":1}', NULL),
    ('9d98485d-0d1e-a4d5-2129-9c326fdd3e4d', N'RELATIONSHIPS', N'REL-007', N'جد لأب', NULL, 1, 6, '25186047-e5d7-6156-a5d1-199c242e4bd2', NULL, NULL, N'{"branch":"paternal","gender":"male","degree":2}', NULL),
    ('c46fbea4-e0e8-73d0-4ea6-0aaefbc88d7d', N'RELATIONSHIPS', N'REL-008', N'جدة لأب', NULL, 1, 7, '25186047-e5d7-6156-a5d1-199c242e4bd2', NULL, NULL, N'{"branch":"paternal","gender":"female","degree":2}', NULL),
    ('1a46e341-8428-f1cc-7345-7e36e52f927b', N'RELATIONSHIPS', N'REL-009', N'جد لأم', NULL, 1, 8, 'f9c1d16b-98d1-5596-fe6d-8df1bc6e7569', NULL, NULL, N'{"branch":"maternal","gender":"male","degree":2}', NULL),
    ('2daa411d-a067-8712-076c-cb1e31434179', N'RELATIONSHIPS', N'REL-010', N'جدة لأم', NULL, 1, 9, 'f9c1d16b-98d1-5596-fe6d-8df1bc6e7569', NULL, NULL, N'{"branch":"maternal","gender":"female","degree":2}', NULL),
    ('21e26a7b-d643-a455-0f60-ec760f6d5340', N'RELATIONSHIPS', N'REL-011', N'عم', NULL, 1, 10, '9d98485d-0d1e-a4d5-2129-9c326fdd3e4d', NULL, NULL, N'{"branch":"paternal","gender":"male","degree":2}', NULL),
    ('680ab11d-09e2-7e0c-4677-ec8a25767646', N'RELATIONSHIPS', N'REL-012', N'عمة', NULL, 1, 11, '9d98485d-0d1e-a4d5-2129-9c326fdd3e4d', NULL, NULL, N'{"branch":"paternal","gender":"female","degree":2}', NULL),
    ('c921692c-852a-817f-1de2-26f71c410eff', N'RELATIONSHIPS', N'REL-013', N'خال', NULL, 1, 12, '1a46e341-8428-f1cc-7345-7e36e52f927b', NULL, NULL, N'{"branch":"maternal","gender":"male","degree":2}', NULL),
    ('8b61ec4c-9e58-2298-f939-52b4231b96e7', N'RELATIONSHIPS', N'REL-014', N'خالة', NULL, 1, 13, '1a46e341-8428-f1cc-7345-7e36e52f927b', NULL, NULL, N'{"branch":"maternal","gender":"female","degree":2}', NULL),
    ('f3a2efff-8e0d-6da4-209d-90cadcc6049c', N'RELATIONSHIPS', N'REL-015', N'ابن الأخ', NULL, 1, 14, '9fb2733b-ee98-de24-67e2-c18093efa149', NULL, NULL, N'{"branch":"self","gender":"male","degree":2}', NULL),
    ('74816903-0da1-c227-9622-bb93c53e634f', N'RELATIONSHIPS', N'REL-016', N'بنت الأخ', NULL, 1, 15, '9fb2733b-ee98-de24-67e2-c18093efa149', NULL, NULL, N'{"branch":"self","gender":"female","degree":2}', NULL),
    ('ac23fe18-349f-852e-35b9-9f30ebce842c', N'RELATIONSHIPS', N'REL-017', N'ابن الأخت', NULL, 1, 16, 'a019dfa8-4620-21dd-4c65-0ae7d0d55b12', NULL, NULL, N'{"branch":"self","gender":"male","degree":2}', NULL),
    ('e96f50a6-a3ba-01d9-9aeb-e2e386713164', N'RELATIONSHIPS', N'REL-018', N'بنت الأخت', NULL, 1, 17, 'a019dfa8-4620-21dd-4c65-0ae7d0d55b12', NULL, NULL, N'{"branch":"self","gender":"female","degree":2}', NULL),
    ('ba802549-3a90-c629-54bf-08cf9ebc7245', N'RELATIONSHIPS', N'REL-019', N'ابن العم', NULL, 1, 18, '21e26a7b-d643-a455-0f60-ec760f6d5340', NULL, NULL, N'{"branch":"paternal","gender":"male","degree":3}', NULL),
    ('f8cd097f-7f5e-0ef4-c02a-ee50b0d97620', N'RELATIONSHIPS', N'REL-020', N'بنت العم', NULL, 1, 19, '21e26a7b-d643-a455-0f60-ec760f6d5340', NULL, NULL, N'{"branch":"paternal","gender":"female","degree":3}', NULL),
    ('9b735b71-6bfc-bb91-900f-696a35b5cc6d', N'RELATIONSHIPS', N'REL-021', N'ابن العمة', NULL, 1, 20, '680ab11d-09e2-7e0c-4677-ec8a25767646', NULL, NULL, N'{"branch":"paternal","gender":"male","degree":3}', NULL),
    ('db9f9ec9-9f19-d945-0052-a9982ebaf4ce', N'RELATIONSHIPS', N'REL-022', N'بنت العمة', NULL, 1, 21, '680ab11d-09e2-7e0c-4677-ec8a25767646', NULL, NULL, N'{"branch":"paternal","gender":"female","degree":3}', NULL),
    ('b06e40db-396a-a1d2-5981-7f70818e6f32', N'RELATIONSHIPS', N'REL-023', N'ابن الخال', NULL, 1, 22, 'c921692c-852a-817f-1de2-26f71c410eff', NULL, NULL, N'{"branch":"maternal","gender":"male","degree":3}', NULL),
    ('b2d4222e-b842-2be5-e0ac-2b01509d4b50', N'RELATIONSHIPS', N'REL-024', N'بنت الخال', NULL, 1, 23, 'c921692c-852a-817f-1de2-26f71c410eff', NULL, NULL, N'{"branch":"maternal","gender":"female","degree":3}', NULL),
    ('d1d85a74-e6d4-71f9-026a-d19fa631395c', N'RELATIONSHIPS', N'REL-025', N'ابن الخالة', NULL, 1, 24, '8b61ec4c-9e58-2298-f939-52b4231b96e7', NULL, NULL, N'{"branch":"maternal","gender":"male","degree":3}', NULL),
    ('24addeed-f711-2c55-c706-8e2c14071126', N'RELATIONSHIPS', N'REL-026', N'بنت الخالة', NULL, 1, 25, '8b61ec4c-9e58-2298-f939-52b4231b96e7', NULL, NULL, N'{"branch":"maternal","gender":"female","degree":3}', NULL),
    ('dd7908d4-36be-2d20-adcb-d67c9a19958f', N'RELATIONSHIPS', N'REL-027', N'جد الأب', NULL, 1, 26, '9d98485d-0d1e-a4d5-2129-9c326fdd3e4d', NULL, NULL, N'{"branch":"paternal","gender":"male","degree":3}', NULL),
    ('4a704385-0921-bbcc-55b8-e1afd7c1a334', N'RELATIONSHIPS', N'REL-028', N'جدة الأب', NULL, 1, 27, 'c46fbea4-e0e8-73d0-4ea6-0aaefbc88d7d', NULL, NULL, N'{"branch":"paternal","gender":"female","degree":3}', NULL),
    ('7cb2d03f-24a7-4f45-c72e-39a1cd3ddf6e', N'RELATIONSHIPS', N'REL-029', N'جد الأم', NULL, 1, 28, '1a46e341-8428-f1cc-7345-7e36e52f927b', NULL, NULL, N'{"branch":"maternal","gender":"male","degree":3}', NULL),
    ('e431cb2b-1833-2e32-1977-10e20ac87407', N'RELATIONSHIPS', N'REL-030', N'جدة الأم', NULL, 1, 29, '2daa411d-a067-8712-076c-cb1e31434179', NULL, NULL, N'{"branch":"maternal","gender":"female","degree":3}', NULL),
    ('904fe457-668e-4c58-dbe0-4a8d1955bf5b', N'RELATIONSHIPS', N'REL-031', N'أبو جد الأب', NULL, 1, 30, 'dd7908d4-36be-2d20-adcb-d67c9a19958f', NULL, NULL, N'{"branch":"paternal","gender":"male","degree":4}', NULL),
    ('c7544d4a-b7d8-6eaa-2ff5-ecbcef46ea3e', N'RELATIONSHIPS', N'REL-032', N'أم جد الأب', NULL, 1, 31, 'dd7908d4-36be-2d20-adcb-d67c9a19958f', NULL, NULL, N'{"branch":"paternal","gender":"female","degree":4}', NULL),
    ('a1a6e6f4-7766-3e56-8f34-d9a7de62fb98', N'RELATIONSHIPS', N'REL-033', N'أبو جد الأم', NULL, 1, 32, '7cb2d03f-24a7-4f45-c72e-39a1cd3ddf6e', NULL, NULL, N'{"branch":"maternal","gender":"male","degree":4}', NULL),
    ('5aece0c0-310e-1fc2-cc5a-ac9748434c90', N'RELATIONSHIPS', N'REL-034', N'أم جد الأم', NULL, 1, 33, '7cb2d03f-24a7-4f45-c72e-39a1cd3ddf6e', NULL, NULL, N'{"branch":"maternal","gender":"female","degree":4}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- RELATIONSHIP_DEGREE_TIERS (4 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('8ed1f043-e6ab-55cc-bdc1-e57539a5931e', N'RELATIONSHIP_DEGREE_TIERS', N'RDT-1', N'الدرجة الأولى', NULL, 1, 0, NULL, NULL, NULL, N'{"degreeRange":"الأقارب من الدرجة الأولى","maxDegree":1}', NULL),
    ('8a2f5763-d014-7457-7ccf-463b13fb46fe', N'RELATIONSHIP_DEGREE_TIERS', N'RDT-2', N'الدرجة الثانية', NULL, 1, 1, NULL, NULL, NULL, N'{"degreeRange":"حتى الدرجة الثانية","maxDegree":2}', NULL),
    ('71195d3e-b35b-b371-2f9b-f9ee58d5ae92', N'RELATIONSHIP_DEGREE_TIERS', N'RDT-3', N'الدرجة الثالثة', NULL, 1, 2, NULL, NULL, NULL, N'{"degreeRange":"حتى الدرجة الثالثة","maxDegree":3}', NULL),
    ('90635c8c-1c5a-e3e1-05e1-6426f81fa8a4', N'RELATIONSHIP_DEGREE_TIERS', N'RDT-4', N'الدرجة الرابعة', NULL, 1, 3, NULL, NULL, NULL, N'{"degreeRange":"حتى الدرجة الرابعة","maxDegree":4}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- TESTS (15 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('e54ba729-ca53-766b-8990-0dbd30511083', N'TESTS', N'TST-01', N'القدرات', NULL, 1, 0, NULL, NULL, NULL, N'{"kind":"written","order":10,"required":true}', NULL),
    ('408e3bbf-0465-a31a-0186-4aa3b4089b63', N'TESTS', N'TST-02', N'المعلومات العامة', NULL, 1, 1, NULL, NULL, NULL, N'{"kind":"written","order":20,"required":true}', NULL),
    ('b84562f9-0dbf-9427-7c39-3e71d8ad5fe6', N'TESTS', N'TST-03', N'الطول', NULL, 1, 2, NULL, NULL, NULL, N'{"kind":"medical","order":30,"required":true}', NULL),
    ('669b6f7c-4fef-efdd-3efc-c8e11131c427', N'TESTS', N'TST-04', N'السمات الخارجية', NULL, 1, 3, NULL, NULL, NULL, N'{"kind":"interview","order":40,"required":true}', NULL),
    ('d21433f2-ddf0-a2e9-191a-6e8e6715fac1', N'TESTS', N'TST-05', N'السمات الداخلية', NULL, 1, 4, NULL, NULL, NULL, N'{"kind":"interview","order":50,"required":true}', NULL),
    ('bfcd2c3f-5acd-00cf-ffcd-6cad955bf11d', N'TESTS', N'TST-06', N'اللياقة الرياضية', NULL, 1, 5, NULL, NULL, NULL, N'{"kind":"physical","order":60,"required":true}', NULL),
    ('626341ef-277d-5d2f-78a3-ab15cac21a28', N'TESTS', N'TST-07', N'إعادة الرياضي', NULL, 1, 6, NULL, NULL, NULL, N'{"kind":"physical","order":70,"required":false}', NULL),
    ('31eecab6-2732-5c8f-b9f4-2ae5000c892d', N'TESTS', N'TST-08', N'الهيئة', NULL, 1, 7, NULL, NULL, NULL, N'{"kind":"interview","order":80,"required":true}', NULL),
    ('964cf82e-c5ec-2f3a-9e1e-a647ab7a3ac9', N'TESTS', N'TST-09', N'القوام', NULL, 1, 8, NULL, NULL, NULL, N'{"kind":"medical","order":90,"required":true}', NULL),
    ('c5f232ba-0fad-a6cd-406d-d527ac59f6af', N'TESTS', N'TST-10', N'إعادة القوام', NULL, 1, 9, NULL, NULL, NULL, N'{"kind":"medical","order":100,"required":false}', NULL),
    ('b120e168-ae2d-9f34-bc23-5c26449ebeb3', N'TESTS', N'TST-11', N'الكشف الطبي', NULL, 1, 10, NULL, NULL, NULL, N'{"kind":"medical","order":110,"required":true}', NULL),
    ('d3cea941-86fc-74e3-ec7f-1f52ad88ba2d', N'TESTS', N'TST-12', N'إعادة الطبي', NULL, 1, 11, NULL, NULL, NULL, N'{"kind":"medical","order":120,"required":false}', NULL),
    ('4588d873-4d98-497c-bc28-ba55c27c95cd', N'TESTS', N'TST-13', N'الاتزان النفسي', NULL, 1, 12, NULL, NULL, NULL, N'{"kind":"psych","order":130,"required":true}', NULL),
    ('e1f7e477-b3a8-49da-3da4-81e9a2b80c02', N'TESTS', N'TST-14', N'الكشف الطبي المتقدم', NULL, 1, 13, NULL, NULL, NULL, N'{"kind":"medical","order":140,"required":true}', NULL),
    ('e576e41c-ea2a-17e7-4895-0536fc33db27', N'TESTS', N'TST-15', N'المقابلة الشخصية', NULL, 1, 14, NULL, NULL, NULL, N'{"kind":"interview","order":150,"required":true}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- TEST_RESULTS (4 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('774fa7e7-1872-8bdc-9fc0-7b1be3fe20a5', N'TEST_RESULTS', N'RES-01', N'ناجح', NULL, 1, 0, NULL, NULL, NULL, N'{"outcome":"pass","tone":"success"}', NULL),
    ('dbcf33d4-34e5-405e-6495-a2136484cc4c', N'TEST_RESULTS', N'RES-02', N'راسب', NULL, 1, 1, NULL, NULL, NULL, N'{"outcome":"fail","tone":"danger"}', NULL),
    ('574a1a45-ea3c-1b36-675e-7981c63e5036', N'TEST_RESULTS', N'RES-03', N'مؤجل', NULL, 1, 2, NULL, NULL, NULL, N'{"outcome":"defer","tone":"warning"}', NULL),
    ('8e1f64a4-9f42-1a90-768d-b005502d11b6', N'TEST_RESULTS', N'RES-04', N'منسحب', NULL, 1, 3, NULL, NULL, NULL, N'{"outcome":"withdrawn","tone":"neutral"}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- COMMITTEES (8 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('523b72ba-74a9-7c86-e8e9-bf743dd1a67b', N'COMMITTEES', N'CMT-01', N'لجنة تسجيل البيانات', NULL, 1, 0, NULL, NULL, NULL, N'{"kind":"primary","chairTitle":"رئيس لجنة التسجيل"}', NULL),
    ('a681d0a1-c55c-3803-2871-628b23e51fde', N'COMMITTEES', N'CMT-02', N'لجنة المقابلة الشخصية', NULL, 1, 1, NULL, NULL, NULL, N'{"kind":"interview","chairTitle":"رئيس لجنة المقابلة"}', NULL),
    ('d0971379-dbd7-e17b-7ec0-bfdfdf0f67a2', N'COMMITTEES', N'CMT-03', N'لجنة القدرات', NULL, 1, 2, NULL, NULL, NULL, N'{"kind":"capacities","chairTitle":"رئيس لجنة القدرات"}', NULL),
    ('6025eabc-93a8-d8e3-84a3-42556c8059b0', N'COMMITTEES', N'CMT-04', N'لجنة السمات', NULL, 1, 3, NULL, NULL, NULL, N'{"kind":"traits","chairTitle":"رئيس لجنة السمات"}', NULL),
    ('dc84f35b-ea80-3326-62e9-cc5535167420', N'COMMITTEES', N'CMT-05', N'لجنة الكشف الطبي', NULL, 1, 4, NULL, NULL, NULL, N'{"kind":"medical","chairTitle":"رئيس القومسيون الطبي"}', NULL),
    ('53f27653-edec-cccd-5eab-023247d4ace6', N'COMMITTEES', N'CMT-06', N'لجنة الكشف الرياضي', NULL, 1, 5, NULL, NULL, NULL, N'{"kind":"sports","chairTitle":"رئيس لجنة الرياضة"}', NULL),
    ('af268a41-a93d-9cb9-ce52-20cbac9f7498', N'COMMITTEES', N'CMT-07', N'لجنة المراجعة النهائية', NULL, 1, 6, NULL, NULL, NULL, N'{"kind":"final","chairTitle":"رئيس لجنة المراجعة"}', NULL),
    ('f77a2a84-d4ee-e793-9c42-60d48650cb0a', N'COMMITTEES', N'CMT-08', N'لجنة التحريات', NULL, 1, 7, NULL, NULL, NULL, N'{"kind":"primary","chairTitle":"رئيس لجنة التحريات"}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- SPECIALIZATIONS (12 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('aa792b62-af9d-d8f6-6fde-b67354f57399', N'SPECIALIZATIONS', N'SPC-01', N'علوم شرطة', NULL, 1, 0, NULL, NULL, NULL, N'{}', N'FAC-01'),
    ('e4563381-f07c-fb65-0d65-2ee309282e55', N'SPECIALIZATIONS', N'SPC-02', N'الأمن العام', NULL, 1, 1, NULL, NULL, NULL, N'{}', N'FAC-01'),
    ('7a299185-3cfe-9452-117b-4dd777658aea', N'SPECIALIZATIONS', N'SPC-03', N'الأمن المركزي', NULL, 1, 2, NULL, NULL, NULL, N'{}', N'FAC-01'),
    ('252edde9-9041-9550-c7f0-4c66dca3df1d', N'SPECIALIZATIONS', N'SPC-04', N'الأمن الإلكتروني', NULL, 1, 3, NULL, NULL, NULL, N'{}', N'FAC-02'),
    ('7b77d2f8-0f41-047f-d9cf-1cd80c57da18', N'SPECIALIZATIONS', N'SPC-05', N'مكافحة المخدرات', NULL, 1, 4, NULL, NULL, NULL, N'{}', N'FAC-02'),
    ('603191ad-6f5e-2198-c09c-f467f27e4ec7', N'SPECIALIZATIONS', N'SPC-06', N'حماية الآداب', NULL, 1, 5, NULL, NULL, NULL, N'{}', N'FAC-02'),
    ('ab19d217-f2e2-91c8-fdeb-bf174bd949b6', N'SPECIALIZATIONS', N'SPC-07', N'المرور', NULL, 1, 6, NULL, NULL, NULL, N'{}', N'FAC-01'),
    ('3aa31679-ac4f-9ba9-c2fd-05c37f958121', N'SPECIALIZATIONS', N'SPC-08', N'الجوازات والهجرة', NULL, 1, 7, NULL, NULL, NULL, N'{}', N'FAC-02'),
    ('816767fa-8c31-e564-abdf-ce84d8bf2940', N'SPECIALIZATIONS', N'SPC-09', N'الأحوال المدنية', NULL, 1, 8, NULL, NULL, NULL, N'{}', N'FAC-04'),
    ('8efdea88-3828-ce2e-1aa8-510871bd22c4', N'SPECIALIZATIONS', N'SPC-10', N'الإدارة العامة', NULL, 1, 9, NULL, NULL, NULL, N'{}', N'FAC-03'),
    ('f3055257-8689-7536-67f4-dc3ebb644aa5', N'SPECIALIZATIONS', N'SPC-11', N'الأمن الاجتماعي', NULL, 1, 10, NULL, NULL, NULL, N'{}', N'FAC-03'),
    ('e0565a99-34a6-6231-18e1-1b25ca099481', N'SPECIALIZATIONS', N'SPC-12', N'مكافحة الإرهاب', NULL, 1, 11, NULL, NULL, NULL, N'{}', N'FAC-02')
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- FACULTIES (4 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('048485ae-b99c-3911-63e1-ce69a209408b', N'FACULTIES', N'FAC-01', N'كلية الضباط', NULL, 1, 0, NULL, NULL, NULL, N'{}', NULL),
    ('422ff07a-46fb-15f8-0aa0-a883eb8c4033', N'FACULTIES', N'FAC-02', N'كلية الضباط المتخصصين', NULL, 1, 1, NULL, NULL, NULL, N'{}', NULL),
    ('193c0274-7aad-f145-cc35-568ee807196f', N'FACULTIES', N'FAC-03', N'كلية الدراسات العليا', NULL, 1, 2, NULL, NULL, NULL, N'{}', NULL),
    ('fdae3ddd-6b9c-5cc3-d31c-c295de2df261', N'FACULTIES', N'FAC-04', N'كلية المعاونين', NULL, 1, 3, NULL, NULL, NULL, N'{}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- APPLICANT_CATEGORIES (8 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('8097520b-454d-92a9-9a5e-7bf99e38f3d6', N'APPLICANT_CATEGORIES', N'CAT-01', N'ثانوية عامة — ذكور', NULL, 1, 0, NULL, NULL, NULL, N'{"genderScope":"male","applicationMode":"general"}', NULL),
    ('594304ce-08b2-67b3-03b0-c3cded254c83', N'APPLICANT_CATEGORIES', N'CAT-02', N'ثانوية عامة — إناث', NULL, 1, 1, NULL, NULL, NULL, N'{"genderScope":"female","applicationMode":"general"}', NULL),
    ('b49f32d0-97b6-09b1-de8c-9fcaccab835c', N'APPLICANT_CATEGORIES', N'CAT-03', N'الأزهر الشريف', NULL, 1, 2, NULL, NULL, NULL, N'{"genderScope":"any","applicationMode":"general"}', NULL),
    ('c122a3b5-d9e9-d643-b643-e8e6f0c8eae6', N'APPLICANT_CATEGORIES', N'CAT-04', N'الضباط المتخصصون', NULL, 1, 3, NULL, NULL, NULL, N'{"genderScope":"any","applicationMode":"nomination"}', NULL),
    ('2cef4c6d-9112-c67a-de5a-20cab2ecbf83', N'APPLICANT_CATEGORIES', N'CAT-05', N'تربية رياضية', NULL, 1, 4, NULL, NULL, NULL, N'{"genderScope":"any","applicationMode":"general"}', NULL),
    ('5e993c2c-15dd-9bc8-ca38-a54308c1f720', N'APPLICANT_CATEGORIES', N'CAT-06', N'حقوق', NULL, 1, 5, NULL, NULL, NULL, N'{"genderScope":"any","applicationMode":"general"}', NULL),
    ('d5b08965-ef10-24fb-8a0f-22f8fad4754c', N'APPLICANT_CATEGORIES', N'CAT-07', N'حاملو شهادات أجنبية', NULL, 1, 6, NULL, NULL, NULL, N'{"genderScope":"any","applicationMode":"general"}', NULL),
    ('ba638fd9-baa6-bd99-ed02-86f59be23b6c', N'APPLICANT_CATEGORIES', N'CAT-08', N'الدراسات العليا', NULL, 1, 7, NULL, NULL, NULL, N'{"genderScope":"any","applicationMode":"nomination"}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- NATIONALITIES_COUNTRIES (56 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('39240b39-b8aa-2d17-1112-142bfb8474ca', N'NATIONALITIES_COUNTRIES', N'CNT-001', N'مصر', NULL, 1, 0, NULL, NULL, NULL, N'{"iso2":"EG","isArab":true}', NULL),
    ('7a5a2cc1-2c1e-8b4d-3eb4-0745c4663d8f', N'NATIONALITIES_COUNTRIES', N'CNT-002', N'السعودية', NULL, 1, 1, NULL, NULL, NULL, N'{"iso2":"SA","isArab":true}', NULL),
    ('56cddea7-a6da-d05e-b27c-ba8557e34a2a', N'NATIONALITIES_COUNTRIES', N'CNT-003', N'الإمارات', NULL, 1, 2, NULL, NULL, NULL, N'{"iso2":"AE","isArab":true}', NULL),
    ('f91f4bb1-c683-0aee-9133-7fe141579738', N'NATIONALITIES_COUNTRIES', N'CNT-004', N'الكويت', NULL, 1, 3, NULL, NULL, NULL, N'{"iso2":"KW","isArab":true}', NULL),
    ('d992b879-b604-1cf5-bcab-f13b4aa39f68', N'NATIONALITIES_COUNTRIES', N'CNT-005', N'قطر', NULL, 1, 4, NULL, NULL, NULL, N'{"iso2":"QA","isArab":true}', NULL),
    ('108fdee7-3ca0-852f-4cd9-f820751419c4', N'NATIONALITIES_COUNTRIES', N'CNT-006', N'البحرين', NULL, 1, 5, NULL, NULL, NULL, N'{"iso2":"BH","isArab":true}', NULL),
    ('e540dc7c-bac6-f1b1-5db1-4008b346112a', N'NATIONALITIES_COUNTRIES', N'CNT-007', N'عُمان', NULL, 1, 6, NULL, NULL, NULL, N'{"iso2":"OM","isArab":true}', NULL),
    ('c1fba3f1-1c12-b039-14be-2a98d087e340', N'NATIONALITIES_COUNTRIES', N'CNT-008', N'الأردن', NULL, 1, 7, NULL, NULL, NULL, N'{"iso2":"JO","isArab":true}', NULL),
    ('fa30ce1e-9e5d-8cb5-c111-679fcc48d0a7', N'NATIONALITIES_COUNTRIES', N'CNT-009', N'فلسطين', NULL, 1, 8, NULL, NULL, NULL, N'{"iso2":"PS","isArab":true}', NULL),
    ('0e5e9b09-6886-07eb-bebb-1245fba62da8', N'NATIONALITIES_COUNTRIES', N'CNT-010', N'سوريا', NULL, 1, 9, NULL, NULL, NULL, N'{"iso2":"SY","isArab":true}', NULL),
    ('8c45aad4-4104-e124-72e7-3716becaa528', N'NATIONALITIES_COUNTRIES', N'CNT-011', N'لبنان', NULL, 1, 10, NULL, NULL, NULL, N'{"iso2":"LB","isArab":true}', NULL),
    ('424a287c-62d1-0e7a-4512-ba387e381d97', N'NATIONALITIES_COUNTRIES', N'CNT-012', N'العراق', NULL, 1, 11, NULL, NULL, NULL, N'{"iso2":"IQ","isArab":true}', NULL),
    ('9d4bdfec-36b0-5c8f-defd-7daf1c62484e', N'NATIONALITIES_COUNTRIES', N'CNT-013', N'ليبيا', NULL, 1, 12, NULL, NULL, NULL, N'{"iso2":"LY","isArab":true}', NULL),
    ('3f3d175e-9652-9a5f-2bf2-db74e7721015', N'NATIONALITIES_COUNTRIES', N'CNT-014', N'السودان', NULL, 1, 13, NULL, NULL, NULL, N'{"iso2":"SD","isArab":true}', NULL),
    ('b80b09fd-43e4-b172-9e96-f6d4bdccb19d', N'NATIONALITIES_COUNTRIES', N'CNT-015', N'اليمن', NULL, 1, 14, NULL, NULL, NULL, N'{"iso2":"YE","isArab":true}', NULL),
    ('4965a38a-3871-0969-9128-2d5f1ea3457e', N'NATIONALITIES_COUNTRIES', N'CNT-016', N'المغرب', NULL, 1, 15, NULL, NULL, NULL, N'{"iso2":"MA","isArab":true}', NULL),
    ('70661a9e-3c9b-399b-592d-429d4122c0d7', N'NATIONALITIES_COUNTRIES', N'CNT-017', N'الجزائر', NULL, 1, 16, NULL, NULL, NULL, N'{"iso2":"DZ","isArab":true}', NULL),
    ('9caabbe5-6ef4-3f0d-c767-1f529b014323', N'NATIONALITIES_COUNTRIES', N'CNT-018', N'تونس', NULL, 1, 17, NULL, NULL, NULL, N'{"iso2":"TN","isArab":true}', NULL),
    ('ac55455c-5143-3ea2-c51a-cd6628d6014c', N'NATIONALITIES_COUNTRIES', N'CNT-019', N'موريتانيا', NULL, 1, 18, NULL, NULL, NULL, N'{"iso2":"MR","isArab":true}', NULL),
    ('bbe57ac5-f303-73e3-8a9f-3c992c838bd8', N'NATIONALITIES_COUNTRIES', N'CNT-020', N'الصومال', NULL, 1, 19, NULL, NULL, NULL, N'{"iso2":"SO","isArab":true}', NULL),
    ('51709bbb-10fa-e191-f2d7-05a27af75f68', N'NATIONALITIES_COUNTRIES', N'CNT-021', N'جيبوتي', NULL, 1, 20, NULL, NULL, NULL, N'{"iso2":"DJ","isArab":true}', NULL),
    ('0a125319-42a2-1255-a4a3-47bd1a29c71c', N'NATIONALITIES_COUNTRIES', N'CNT-022', N'جزر القمر', NULL, 1, 21, NULL, NULL, NULL, N'{"iso2":"KM","isArab":true}', NULL),
    ('ab4b0dad-baa1-d0e7-d09d-951892c31871', N'NATIONALITIES_COUNTRIES', N'CNT-023', N'الولايات المتحدة', NULL, 1, 22, NULL, NULL, NULL, N'{"iso2":"US","isArab":false}', NULL),
    ('cfc4f854-1e25-3ef1-9c4c-36822f3f4f84', N'NATIONALITIES_COUNTRIES', N'CNT-024', N'كندا', NULL, 1, 23, NULL, NULL, NULL, N'{"iso2":"CA","isArab":false}', NULL),
    ('fd9ac10d-3d5b-d90e-42e5-25619095697e', N'NATIONALITIES_COUNTRIES', N'CNT-025', N'المملكة المتحدة', NULL, 1, 24, NULL, NULL, NULL, N'{"iso2":"GB","isArab":false}', NULL),
    ('351e7498-b981-6bb3-f3c2-78e0b83173f9', N'NATIONALITIES_COUNTRIES', N'CNT-026', N'فرنسا', NULL, 1, 25, NULL, NULL, NULL, N'{"iso2":"FR","isArab":false}', NULL),
    ('c73caa98-4f63-702e-c08a-cd239da1b436', N'NATIONALITIES_COUNTRIES', N'CNT-027', N'ألمانيا', NULL, 1, 26, NULL, NULL, NULL, N'{"iso2":"DE","isArab":false}', NULL),
    ('288c148c-8597-fa5d-be6a-f0b667496341', N'NATIONALITIES_COUNTRIES', N'CNT-028', N'إيطاليا', NULL, 1, 27, NULL, NULL, NULL, N'{"iso2":"IT","isArab":false}', NULL),
    ('b9e0a142-bc2e-413e-7391-21c7628d719a', N'NATIONALITIES_COUNTRIES', N'CNT-029', N'إسبانيا', NULL, 1, 28, NULL, NULL, NULL, N'{"iso2":"ES","isArab":false}', NULL),
    ('4e0fdafa-694c-4484-caee-7502c766d051', N'NATIONALITIES_COUNTRIES', N'CNT-030', N'البرتغال', NULL, 1, 29, NULL, NULL, NULL, N'{"iso2":"PT","isArab":false}', NULL),
    ('b56ea976-c99c-7845-5533-8a7e1eed3b0e', N'NATIONALITIES_COUNTRIES', N'CNT-031', N'هولندا', NULL, 1, 30, NULL, NULL, NULL, N'{"iso2":"NL","isArab":false}', NULL),
    ('465cdc1f-ded2-6e94-d897-1162005d6a5e', N'NATIONALITIES_COUNTRIES', N'CNT-032', N'بلجيكا', NULL, 1, 31, NULL, NULL, NULL, N'{"iso2":"BE","isArab":false}', NULL),
    ('fff9f8e3-3a3a-53fb-16d4-bd644ce1ee89', N'NATIONALITIES_COUNTRIES', N'CNT-033', N'سويسرا', NULL, 1, 32, NULL, NULL, NULL, N'{"iso2":"CH","isArab":false}', NULL),
    ('355f2a83-1eca-cb71-d62d-cb59f4746422', N'NATIONALITIES_COUNTRIES', N'CNT-034', N'النمسا', NULL, 1, 33, NULL, NULL, NULL, N'{"iso2":"AT","isArab":false}', NULL),
    ('33dfadea-f2ee-f8ae-c083-e6885672f36c', N'NATIONALITIES_COUNTRIES', N'CNT-035', N'السويد', NULL, 1, 34, NULL, NULL, NULL, N'{"iso2":"SE","isArab":false}', NULL),
    ('79e2bed9-09b1-20e2-c34a-f4e5fc6c7c7b', N'NATIONALITIES_COUNTRIES', N'CNT-036', N'الدنمارك', NULL, 1, 35, NULL, NULL, NULL, N'{"iso2":"DK","isArab":false}', NULL),
    ('baba2f2d-0e26-9340-92dd-38f73734f1c2', N'NATIONALITIES_COUNTRIES', N'CNT-037', N'النرويج', NULL, 1, 36, NULL, NULL, NULL, N'{"iso2":"NO","isArab":false}', NULL),
    ('78bc6d2e-a45f-664e-f1e6-932af8e62404', N'NATIONALITIES_COUNTRIES', N'CNT-038', N'فنلندا', NULL, 1, 37, NULL, NULL, NULL, N'{"iso2":"FI","isArab":false}', NULL),
    ('7e034324-ae60-b99c-74f4-54db31329e5f', N'NATIONALITIES_COUNTRIES', N'CNT-039', N'بولندا', NULL, 1, 38, NULL, NULL, NULL, N'{"iso2":"PL","isArab":false}', NULL),
    ('472417a7-0a26-ea91-eb48-fb904499c983', N'NATIONALITIES_COUNTRIES', N'CNT-040', N'روسيا', NULL, 1, 39, NULL, NULL, NULL, N'{"iso2":"RU","isArab":false}', NULL),
    ('f74d7297-1bfd-2811-5e42-a902f7428498', N'NATIONALITIES_COUNTRIES', N'CNT-041', N'أوكرانيا', NULL, 1, 40, NULL, NULL, NULL, N'{"iso2":"UA","isArab":false}', NULL),
    ('fdda4c59-fd0e-3cc5-d835-a37b34e2d8bd', N'NATIONALITIES_COUNTRIES', N'CNT-042', N'تركيا', NULL, 1, 41, NULL, NULL, NULL, N'{"iso2":"TR","isArab":false}', NULL),
    ('1f4d2792-bb29-3718-fbc2-66fa364f109a', N'NATIONALITIES_COUNTRIES', N'CNT-043', N'إيران', NULL, 1, 42, NULL, NULL, NULL, N'{"iso2":"IR","isArab":false}', NULL),
    ('48cff54c-d0a3-5c78-e153-f9f97a7db6b4', N'NATIONALITIES_COUNTRIES', N'CNT-044', N'باكستان', NULL, 1, 43, NULL, NULL, NULL, N'{"iso2":"PK","isArab":false}', NULL),
    ('f3425eca-9e1b-66a7-8c50-fdc80c3c12be', N'NATIONALITIES_COUNTRIES', N'CNT-045', N'الهند', NULL, 1, 44, NULL, NULL, NULL, N'{"iso2":"IN","isArab":false}', NULL),
    ('04a39a0f-2dab-6065-1480-f54da7bdae6b', N'NATIONALITIES_COUNTRIES', N'CNT-046', N'بنغلاديش', NULL, 1, 45, NULL, NULL, NULL, N'{"iso2":"BD","isArab":false}', NULL),
    ('8c8cd93b-b8ba-99be-fe67-c6d84d18c209', N'NATIONALITIES_COUNTRIES', N'CNT-047', N'إندونيسيا', NULL, 1, 46, NULL, NULL, NULL, N'{"iso2":"ID","isArab":false}', NULL),
    ('13752180-6166-50a0-3dee-9891a862f6b8', N'NATIONALITIES_COUNTRIES', N'CNT-048', N'ماليزيا', NULL, 1, 47, NULL, NULL, NULL, N'{"iso2":"MY","isArab":false}', NULL),
    ('e3f0750a-4c1e-8856-6714-1375319478c8', N'NATIONALITIES_COUNTRIES', N'CNT-049', N'الصين', NULL, 1, 48, NULL, NULL, NULL, N'{"iso2":"CN","isArab":false}', NULL),
    ('1b602d3f-6664-ac0b-936d-bbb5aff832af', N'NATIONALITIES_COUNTRIES', N'CNT-050', N'اليابان', NULL, 1, 49, NULL, NULL, NULL, N'{"iso2":"JP","isArab":false}', NULL),
    ('00f963b9-a0d6-eb0e-a263-fdae584ae82d', N'NATIONALITIES_COUNTRIES', N'CNT-051', N'كوريا الجنوبية', NULL, 1, 50, NULL, NULL, NULL, N'{"iso2":"KR","isArab":false}', NULL),
    ('9cf89615-93b9-f57d-1f3c-a4103c95ac1d', N'NATIONALITIES_COUNTRIES', N'CNT-052', N'أستراليا', NULL, 1, 51, NULL, NULL, NULL, N'{"iso2":"AU","isArab":false}', NULL),
    ('5440389b-3f52-927b-fe38-ccf8adeb6c1a', N'NATIONALITIES_COUNTRIES', N'CNT-053', N'نيجيريا', NULL, 1, 52, NULL, NULL, NULL, N'{"iso2":"NG","isArab":false}', NULL),
    ('e0cdbeea-2908-9010-07ab-9f894a32f15c', N'NATIONALITIES_COUNTRIES', N'CNT-054', N'إثيوبيا', NULL, 1, 53, NULL, NULL, NULL, N'{"iso2":"ET","isArab":false}', NULL),
    ('832c3bfe-e25e-93ef-e764-a8a924dbc879', N'NATIONALITIES_COUNTRIES', N'CNT-055', N'كينيا', NULL, 1, 54, NULL, NULL, NULL, N'{"iso2":"KE","isArab":false}', NULL),
    ('ffd08373-759b-4209-d3ea-58c5f8270b83', N'NATIONALITIES_COUNTRIES', N'CNT-056', N'جنوب أفريقيا', NULL, 1, 55, NULL, NULL, NULL, N'{"iso2":"ZA","isArab":false}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- GOVERNORATES (27 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('b636921b-8e67-1152-73fa-873b80ce1eda', N'GOVERNORATES', N'GOV-01', N'القاهرة', NULL, 1, 0, NULL, NULL, NULL, N'{"region":"القاهرة الكبرى"}', NULL),
    ('0ba7b915-4284-3d98-3bb2-88c896fd2548', N'GOVERNORATES', N'GOV-02', N'الجيزة', NULL, 1, 1, NULL, NULL, NULL, N'{"region":"القاهرة الكبرى"}', NULL),
    ('dea7ba48-57d3-26a1-8eba-d697871668a9', N'GOVERNORATES', N'GOV-03', N'القليوبية', NULL, 1, 2, NULL, NULL, NULL, N'{"region":"القاهرة الكبرى"}', NULL),
    ('c3c783bb-ea7d-aaf7-5168-6be151c6b6cb', N'GOVERNORATES', N'GOV-04', N'الإسكندرية', NULL, 1, 3, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('c5bf7eb5-409b-88c8-5baf-08d943ba343d', N'GOVERNORATES', N'GOV-05', N'الدقهلية', NULL, 1, 4, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('a1cc88b2-e7bf-8af6-11ed-8e6f35f9af8f', N'GOVERNORATES', N'GOV-06', N'الشرقية', NULL, 1, 5, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('59e74473-c271-4e32-7be9-8d09057d6c8f', N'GOVERNORATES', N'GOV-07', N'المنوفية', NULL, 1, 6, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('0ca697de-5fd5-56e8-146c-fc8a895aee78', N'GOVERNORATES', N'GOV-08', N'البحيرة', NULL, 1, 7, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('220176a4-2e78-7d99-ab3b-b2edb0d6f435', N'GOVERNORATES', N'GOV-09', N'الغربية', NULL, 1, 8, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('7cc30272-cec4-8f25-6dbc-37dd7fe66907', N'GOVERNORATES', N'GOV-10', N'كفر الشيخ', NULL, 1, 9, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('13f188a2-dd08-a889-40cf-901885560406', N'GOVERNORATES', N'GOV-11', N'دمياط', NULL, 1, 10, NULL, NULL, NULL, N'{"region":"الوجه البحري"}', NULL),
    ('220af520-55d6-0c6a-8df4-5ea3dadc6c0a', N'GOVERNORATES', N'GOV-12', N'بني سويف', NULL, 1, 11, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('a12bdd17-5500-77ec-09bf-f3e1bb4caf2b', N'GOVERNORATES', N'GOV-13', N'الفيوم', NULL, 1, 12, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('76a678c2-c3f7-045c-a202-a844e8e5b72c', N'GOVERNORATES', N'GOV-14', N'المنيا', NULL, 1, 13, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('df950357-8e9b-2965-ed71-310ec923e4c9', N'GOVERNORATES', N'GOV-15', N'أسيوط', NULL, 1, 14, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('d475b5c9-1fcf-6c9b-33c5-865559a99e11', N'GOVERNORATES', N'GOV-16', N'سوهاج', NULL, 1, 15, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('ae70a2eb-1e42-9170-49ef-5c004e2dc4cb', N'GOVERNORATES', N'GOV-17', N'قنا', NULL, 1, 16, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('bdf5592b-55b6-ca6b-c06e-aecafc653297', N'GOVERNORATES', N'GOV-18', N'الأقصر', NULL, 1, 17, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('f701f74a-8b50-7cb5-5e28-1d88ce0affb1', N'GOVERNORATES', N'GOV-19', N'أسوان', NULL, 1, 18, NULL, NULL, NULL, N'{"region":"الوجه القبلي"}', NULL),
    ('47e997a7-f340-e7ce-f09b-239ebc4b4bb9', N'GOVERNORATES', N'GOV-20', N'بورسعيد', NULL, 1, 19, NULL, NULL, NULL, N'{"region":"القناة"}', NULL),
    ('cb68fd80-6015-5f6a-898e-dadccf4e4cb0', N'GOVERNORATES', N'GOV-21', N'الإسماعيلية', NULL, 1, 20, NULL, NULL, NULL, N'{"region":"القناة"}', NULL),
    ('aa1e16ae-807d-341d-ccb6-cb2f12bfe0de', N'GOVERNORATES', N'GOV-22', N'السويس', NULL, 1, 21, NULL, NULL, NULL, N'{"region":"القناة"}', NULL),
    ('b60c9ac0-852d-9342-0d88-437dab50c54e', N'GOVERNORATES', N'GOV-23', N'البحر الأحمر', NULL, 1, 22, NULL, NULL, NULL, N'{"region":"الحدود"}', NULL),
    ('bb52fb9d-589a-2efe-87e3-77a7953fd44a', N'GOVERNORATES', N'GOV-24', N'الوادي الجديد', NULL, 1, 23, NULL, NULL, NULL, N'{"region":"الحدود"}', NULL),
    ('3566a19c-cddd-3bd6-db91-49811808d130', N'GOVERNORATES', N'GOV-25', N'مرسى مطروح', NULL, 1, 24, NULL, NULL, NULL, N'{"region":"الحدود"}', NULL),
    ('1ccab0a8-14b2-fdbc-0da9-5b673d987841', N'GOVERNORATES', N'GOV-26', N'شمال سيناء', NULL, 1, 25, NULL, NULL, NULL, N'{"region":"الحدود"}', NULL),
    ('6ce886fb-c317-437d-8686-67e1bf02ba9c', N'GOVERNORATES', N'GOV-27', N'جنوب سيناء', NULL, 1, 26, NULL, NULL, NULL, N'{"region":"الحدود"}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- POLICE_STATIONS (64 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('ad5250e6-1ea5-a372-8709-dc1c1d4afb97', N'POLICE_STATIONS', N'PST-0001', N'قسم عابدين', NULL, 1, 0, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('0ae39c32-1349-2146-8597-668c73205516', N'POLICE_STATIONS', N'PST-0002', N'قسم السيدة زينب', NULL, 1, 1, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('8286bf9c-6818-72b3-3822-3949c4d6f6d5', N'POLICE_STATIONS', N'PST-0003', N'قسم مصر القديمة', NULL, 1, 2, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('f31f9b2d-2535-1c96-9bbc-f52eb63436c9', N'POLICE_STATIONS', N'PST-0004', N'قسم النزهة', NULL, 1, 3, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('8b7bee9a-f94a-b00f-3310-0b6fd2ffa758', N'POLICE_STATIONS', N'PST-0005', N'قسم مدينة نصر أول', NULL, 1, 4, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('857dbfc3-feb2-4244-271a-bbd182586a6c', N'POLICE_STATIONS', N'PST-0006', N'قسم مصر الجديدة', NULL, 1, 5, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('7c81c15f-40dd-044c-f8ed-82b1455f0ec5', N'POLICE_STATIONS', N'PST-0007', N'قسم المعادي', NULL, 1, 6, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('f0070b87-beb6-6665-5067-0a30866b84a9', N'POLICE_STATIONS', N'PST-0008', N'قسم حلوان', NULL, 1, 7, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('eb17add5-5f30-16e7-4a5a-890d7ff6c6ca', N'POLICE_STATIONS', N'PST-0009', N'قسم شبرا', NULL, 1, 8, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('3d927c8b-9183-5de8-02c9-e0f31ca1b84b', N'POLICE_STATIONS', N'PST-0010', N'قسم الزيتون', NULL, 1, 9, NULL, NULL, NULL, N'{"governorateCode":"GOV-01","kind":"قسم"}', NULL),
    ('446c020f-7071-18a6-f71b-fa6a4db32639', N'POLICE_STATIONS', N'PST-0011', N'قسم الدقي', NULL, 1, 10, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"قسم"}', NULL),
    ('1336fcda-c58b-5fda-13ed-dfaf90dba856', N'POLICE_STATIONS', N'PST-0012', N'قسم العجوزة', NULL, 1, 11, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"قسم"}', NULL),
    ('c099361a-a3f1-0eda-7b3e-3dc565677550', N'POLICE_STATIONS', N'PST-0013', N'قسم العمرانية', NULL, 1, 12, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"قسم"}', NULL),
    ('a2088567-4f9a-e234-b1c4-de3e95606d9b', N'POLICE_STATIONS', N'PST-0014', N'قسم بولاق الدكرور', NULL, 1, 13, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"قسم"}', NULL),
    ('08ebee49-bda4-6f7d-7061-bf5e4e2ffdc6', N'POLICE_STATIONS', N'PST-0015', N'قسم الهرم', NULL, 1, 14, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"قسم"}', NULL),
    ('207220a9-910e-bdea-204f-039caca8325e', N'POLICE_STATIONS', N'PST-0016', N'مركز إمبابة', NULL, 1, 15, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"مركز"}', NULL),
    ('599e6fdd-45cc-bbb2-36f6-f99293809d01', N'POLICE_STATIONS', N'PST-0017', N'مركز كرداسة', NULL, 1, 16, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"مركز"}', NULL),
    ('c77ba515-2d71-d68f-a65f-7118e6363168', N'POLICE_STATIONS', N'PST-0018', N'مركز أوسيم', NULL, 1, 17, NULL, NULL, NULL, N'{"governorateCode":"GOV-02","kind":"مركز"}', NULL),
    ('f80a8cf3-1c9e-0dc4-948c-92ebc1413e26', N'POLICE_STATIONS', N'PST-0019', N'قسم بنها', NULL, 1, 18, NULL, NULL, NULL, N'{"governorateCode":"GOV-03","kind":"قسم"}', NULL),
    ('44489cdc-cec1-f152-b0cc-0c246a730c57', N'POLICE_STATIONS', N'PST-0020', N'قسم القناطر الخيرية', NULL, 1, 19, NULL, NULL, NULL, N'{"governorateCode":"GOV-03","kind":"قسم"}', NULL),
    ('66db7192-a92a-130e-7c12-3374d71816fc', N'POLICE_STATIONS', N'PST-0021', N'مركز شبرا الخيمة', NULL, 1, 20, NULL, NULL, NULL, N'{"governorateCode":"GOV-03","kind":"مركز"}', NULL),
    ('ca7473db-89fe-0474-8b1b-fd96f1332b92', N'POLICE_STATIONS', N'PST-0022', N'مركز قها', NULL, 1, 21, NULL, NULL, NULL, N'{"governorateCode":"GOV-03","kind":"مركز"}', NULL),
    ('5314f2a6-e941-3add-9346-5562d2f67a67', N'POLICE_STATIONS', N'PST-0023', N'قسم محرم بك', NULL, 1, 22, NULL, NULL, NULL, N'{"governorateCode":"GOV-04","kind":"قسم"}', NULL),
    ('a1805285-4e80-c61d-6f5d-a0f07bb60755', N'POLICE_STATIONS', N'PST-0024', N'قسم سيدي جابر', NULL, 1, 23, NULL, NULL, NULL, N'{"governorateCode":"GOV-04","kind":"قسم"}', NULL),
    ('d03886de-6706-1189-e1fa-85b3e33be079', N'POLICE_STATIONS', N'PST-0025', N'قسم الرمل', NULL, 1, 24, NULL, NULL, NULL, N'{"governorateCode":"GOV-04","kind":"قسم"}', NULL),
    ('61c9312f-64ac-e4c1-df32-beaec0ce104f', N'POLICE_STATIONS', N'PST-0026', N'قسم المنتزة', NULL, 1, 25, NULL, NULL, NULL, N'{"governorateCode":"GOV-04","kind":"قسم"}', NULL),
    ('0ede322a-4a97-cc91-25ef-16123cd6fdd8', N'POLICE_STATIONS', N'PST-0027', N'قسم العامرية', NULL, 1, 26, NULL, NULL, NULL, N'{"governorateCode":"GOV-04","kind":"قسم"}', NULL),
    ('7014b40d-426d-b7a8-908f-eb95b9085efb', N'POLICE_STATIONS', N'PST-0028', N'قسم العطارين', NULL, 1, 27, NULL, NULL, NULL, N'{"governorateCode":"GOV-04","kind":"قسم"}', NULL),
    ('4e5b0a47-2634-b207-8f44-74535e9d1dd0', N'POLICE_STATIONS', N'PST-0029', N'قسم أول المنصورة', NULL, 1, 28, NULL, NULL, NULL, N'{"governorateCode":"GOV-05","kind":"قسم"}', NULL),
    ('c97553ea-a753-94f4-ded1-ad0eaa834b81', N'POLICE_STATIONS', N'PST-0030', N'قسم ثاني المنصورة', NULL, 1, 29, NULL, NULL, NULL, N'{"governorateCode":"GOV-05","kind":"قسم"}', NULL),
    ('356cba49-ba66-25e0-fd46-d18dd7c696e5', N'POLICE_STATIONS', N'PST-0031', N'مركز ميت غمر', NULL, 1, 30, NULL, NULL, NULL, N'{"governorateCode":"GOV-05","kind":"مركز"}', NULL),
    ('ffeab848-78ee-67b9-87a1-297bdde3921d', N'POLICE_STATIONS', N'PST-0032', N'مركز السنبلاوين', NULL, 1, 31, NULL, NULL, NULL, N'{"governorateCode":"GOV-05","kind":"مركز"}', NULL),
    ('35a2405d-71cd-ae68-d004-7763641444bd', N'POLICE_STATIONS', N'PST-0033', N'قسم أول الزقازيق', NULL, 1, 32, NULL, NULL, NULL, N'{"governorateCode":"GOV-06","kind":"قسم"}', NULL),
    ('090d4a7d-2afe-dc5a-1af0-811fb5c1aad8', N'POLICE_STATIONS', N'PST-0034', N'قسم ثاني الزقازيق', NULL, 1, 33, NULL, NULL, NULL, N'{"governorateCode":"GOV-06","kind":"قسم"}', NULL),
    ('ba22bc7a-dacc-1ac1-882d-9740c6e2632e', N'POLICE_STATIONS', N'PST-0035', N'مركز بلبيس', NULL, 1, 34, NULL, NULL, NULL, N'{"governorateCode":"GOV-06","kind":"مركز"}', NULL),
    ('af6f13c9-d1b5-ad4c-c6e0-ad2a9fc6b6c2', N'POLICE_STATIONS', N'PST-0036', N'مركز فاقوس', NULL, 1, 35, NULL, NULL, NULL, N'{"governorateCode":"GOV-06","kind":"مركز"}', NULL),
    ('0e1b39ef-1f1e-8b2b-c265-193e319aab15', N'POLICE_STATIONS', N'PST-0037', N'مركز أبو حماد', NULL, 1, 36, NULL, NULL, NULL, N'{"governorateCode":"GOV-06","kind":"مركز"}', NULL),
    ('df53b663-4dbd-c054-d50c-43753331836d', N'POLICE_STATIONS', N'PST-0038', N'قسم شبين الكوم', NULL, 1, 37, NULL, NULL, NULL, N'{"governorateCode":"GOV-07","kind":"قسم"}', NULL),
    ('58bbffef-0282-f676-824d-b47a895e0bb5', N'POLICE_STATIONS', N'PST-0039', N'مركز منوف', NULL, 1, 38, NULL, NULL, NULL, N'{"governorateCode":"GOV-07","kind":"مركز"}', NULL),
    ('cdfbe017-7839-b812-946a-d319b23dcc5a', N'POLICE_STATIONS', N'PST-0040', N'مركز قويسنا', NULL, 1, 39, NULL, NULL, NULL, N'{"governorateCode":"GOV-07","kind":"مركز"}', NULL),
    ('8dde777d-20d9-83d1-839d-9aff68c578c1', N'POLICE_STATIONS', N'PST-0041', N'قسم دمنهور', NULL, 1, 40, NULL, NULL, NULL, N'{"governorateCode":"GOV-08","kind":"قسم"}', NULL),
    ('87020071-32cb-5c2e-5df1-b0f8bfa2e5dd', N'POLICE_STATIONS', N'PST-0042', N'مركز كفر الدوار', NULL, 1, 41, NULL, NULL, NULL, N'{"governorateCode":"GOV-08","kind":"مركز"}', NULL),
    ('435a643c-23dc-d153-e575-671b5ee9dc64', N'POLICE_STATIONS', N'PST-0043', N'مركز إيتاي البارود', NULL, 1, 42, NULL, NULL, NULL, N'{"governorateCode":"GOV-08","kind":"مركز"}', NULL),
    ('38904209-82e7-5c1f-9940-43a4a90a225d', N'POLICE_STATIONS', N'PST-0044', N'قسم أول طنطا', NULL, 1, 43, NULL, NULL, NULL, N'{"governorateCode":"GOV-09","kind":"قسم"}', NULL),
    ('abd49a61-7cc7-6030-db35-082bc2f549fa', N'POLICE_STATIONS', N'PST-0045', N'قسم ثاني طنطا', NULL, 1, 44, NULL, NULL, NULL, N'{"governorateCode":"GOV-09","kind":"قسم"}', NULL),
    ('bef24d70-4308-5796-3003-ba1eb0096626', N'POLICE_STATIONS', N'PST-0046', N'قسم المحلة الكبرى', NULL, 1, 45, NULL, NULL, NULL, N'{"governorateCode":"GOV-09","kind":"قسم"}', NULL),
    ('152167a2-9ebd-61c3-bc6b-4b7bb2361c3e', N'POLICE_STATIONS', N'PST-0047', N'قسم كفر الشيخ', NULL, 1, 46, NULL, NULL, NULL, N'{"governorateCode":"GOV-10","kind":"قسم"}', NULL),
    ('885ad593-8eef-c7d3-9879-b8e4f7436c86', N'POLICE_STATIONS', N'PST-0048', N'مركز دسوق', NULL, 1, 47, NULL, NULL, NULL, N'{"governorateCode":"GOV-10","kind":"مركز"}', NULL),
    ('2b3408df-c0ce-1d89-9f0d-627843ff20a5', N'POLICE_STATIONS', N'PST-0049', N'قسم دمياط', NULL, 1, 48, NULL, NULL, NULL, N'{"governorateCode":"GOV-11","kind":"قسم"}', NULL),
    ('4aa8110e-9c81-8fdc-3b69-1501cb7b2871', N'POLICE_STATIONS', N'PST-0050', N'بندر فارسكور', NULL, 1, 49, NULL, NULL, NULL, N'{"governorateCode":"GOV-11","kind":"بندر"}', NULL),
    ('045e3951-bf8c-6f50-62c6-a721ae3fc0d2', N'POLICE_STATIONS', N'PST-0051', N'قسم أول أسيوط', NULL, 1, 50, NULL, NULL, NULL, N'{"governorateCode":"GOV-15","kind":"قسم"}', NULL),
    ('52879745-5012-2bac-9535-8ae5e6379ab2', N'POLICE_STATIONS', N'PST-0052', N'مركز ديروط', NULL, 1, 51, NULL, NULL, NULL, N'{"governorateCode":"GOV-15","kind":"مركز"}', NULL),
    ('c28ee166-9390-8b02-132e-9ce3e696c3fa', N'POLICE_STATIONS', N'PST-0053', N'مركز منفلوط', NULL, 1, 52, NULL, NULL, NULL, N'{"governorateCode":"GOV-15","kind":"مركز"}', NULL),
    ('57889207-531f-97e3-1524-a998e9f4b5c7', N'POLICE_STATIONS', N'PST-0054', N'قسم سوهاج', NULL, 1, 53, NULL, NULL, NULL, N'{"governorateCode":"GOV-16","kind":"قسم"}', NULL),
    ('1731c86d-c74d-7708-d935-d61bd23df6b0', N'POLICE_STATIONS', N'PST-0055', N'مركز جرجا', NULL, 1, 54, NULL, NULL, NULL, N'{"governorateCode":"GOV-16","kind":"مركز"}', NULL),
    ('0f2cdd9f-5796-c0db-f491-81aedca05eb3', N'POLICE_STATIONS', N'PST-0056', N'قسم قنا', NULL, 1, 55, NULL, NULL, NULL, N'{"governorateCode":"GOV-17","kind":"قسم"}', NULL),
    ('925b4543-3338-87ce-6d6f-f8d2bcb945d5', N'POLICE_STATIONS', N'PST-0057', N'مركز قوص', NULL, 1, 56, NULL, NULL, NULL, N'{"governorateCode":"GOV-17","kind":"مركز"}', NULL),
    ('140d6e15-9341-640b-accf-5bf9d0d6fd12', N'POLICE_STATIONS', N'PST-0058', N'قسم الأقصر', NULL, 1, 57, NULL, NULL, NULL, N'{"governorateCode":"GOV-18","kind":"قسم"}', NULL),
    ('13ed6a8c-b573-cde3-38ea-baa2b8207c65', N'POLICE_STATIONS', N'PST-0059', N'قسم أسوان', NULL, 1, 58, NULL, NULL, NULL, N'{"governorateCode":"GOV-19","kind":"قسم"}', NULL),
    ('e863368b-2337-d290-4499-0d4e5973c209', N'POLICE_STATIONS', N'PST-0060', N'مركز كوم أمبو', NULL, 1, 59, NULL, NULL, NULL, N'{"governorateCode":"GOV-19","kind":"مركز"}', NULL),
    ('5d25c6a6-d6d3-3f26-9349-386d6a0867ce', N'POLICE_STATIONS', N'PST-0061', N'قسم بورسعيد', NULL, 1, 60, NULL, NULL, NULL, N'{"governorateCode":"GOV-20","kind":"قسم"}', NULL),
    ('781084e4-b6f5-4675-20e7-b96159a7ac52', N'POLICE_STATIONS', N'PST-0062', N'قسم الشرق', NULL, 1, 61, NULL, NULL, NULL, N'{"governorateCode":"GOV-20","kind":"قسم"}', NULL),
    ('3e5e7f6f-6c76-8027-51e1-5be533bb88d5', N'POLICE_STATIONS', N'PST-0063', N'قسم الإسماعيلية', NULL, 1, 62, NULL, NULL, NULL, N'{"governorateCode":"GOV-21","kind":"قسم"}', NULL),
    ('dd38af7a-daeb-c702-f910-a3d8b42f8e6e', N'POLICE_STATIONS', N'PST-0064', N'قسم السويس', NULL, 1, 63, NULL, NULL, NULL, N'{"governorateCode":"GOV-22","kind":"قسم"}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- JOBS (25 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('3ab4459b-a24d-1ecf-32b3-abd1d9b2ec17', N'JOBS', N'JOB-001', N'وظائف حكومية', NULL, 1, 0, NULL, NULL, NULL, N'{}', NULL),
    ('40106646-6666-8e23-d881-4bc05c16912a', N'JOBS', N'JOB-002', N'وظائف القطاع الخاص', NULL, 1, 1, NULL, NULL, NULL, N'{}', NULL),
    ('dd1b30b2-b42e-5efb-4d82-ac338fee30e7', N'JOBS', N'JOB-003', N'مهن حرة', NULL, 1, 2, NULL, NULL, NULL, N'{}', NULL),
    ('d7dc0765-809d-b249-d14d-32856bba3c8a', N'JOBS', N'JOB-004', N'الجهات العسكرية', NULL, 1, 3, NULL, NULL, NULL, N'{}', NULL),
    ('303c4078-e52b-5d62-050e-90a1b050de68', N'JOBS', N'JOB-101', N'مدرّس', NULL, 1, 4, '3ab4459b-a24d-1ecf-32b3-abd1d9b2ec17', NULL, NULL, N'{}', NULL),
    ('3abefc18-21f8-7d76-4664-93502b680ae0', N'JOBS', N'JOB-102', N'موظف حكومي', NULL, 1, 5, '3ab4459b-a24d-1ecf-32b3-abd1d9b2ec17', NULL, NULL, N'{}', NULL),
    ('ec2f3023-b82c-27be-4e2b-aa1ce5e8d61a', N'JOBS', N'JOB-103', N'طبيب حكومي', NULL, 1, 6, '3ab4459b-a24d-1ecf-32b3-abd1d9b2ec17', NULL, NULL, N'{}', NULL),
    ('8b9ae020-a59a-1f76-16cd-f9157f78cdb5', N'JOBS', N'JOB-104', N'مهندس حكومي', NULL, 1, 7, '3ab4459b-a24d-1ecf-32b3-abd1d9b2ec17', NULL, NULL, N'{}', NULL),
    ('dbad1652-0118-bc6b-a979-51f32652ba3e', N'JOBS', N'JOB-105', N'محاسب حكومي', NULL, 1, 8, '3ab4459b-a24d-1ecf-32b3-abd1d9b2ec17', NULL, NULL, N'{}', NULL),
    ('2fc8628d-0ff6-3584-03e3-a68062dfeba3', N'JOBS', N'JOB-106', N'قاضٍ', NULL, 1, 9, '3ab4459b-a24d-1ecf-32b3-abd1d9b2ec17', NULL, NULL, N'{}', NULL),
    ('deb9b8f8-6a53-6366-a4c5-eaa14eb58a23', N'JOBS', N'JOB-201', N'موظف قطاع خاص', NULL, 1, 10, '40106646-6666-8e23-d881-4bc05c16912a', NULL, NULL, N'{}', NULL),
    ('a9c6377e-190f-1fb1-8b92-36120d9a56bd', N'JOBS', N'JOB-202', N'رجل أعمال', NULL, 1, 11, '40106646-6666-8e23-d881-4bc05c16912a', NULL, NULL, N'{}', NULL),
    ('dcd81ff8-6cac-8c30-cfb9-dacba6b0ee35', N'JOBS', N'JOB-203', N'مدير شركة', NULL, 1, 12, '40106646-6666-8e23-d881-4bc05c16912a', NULL, NULL, N'{}', NULL),
    ('6da50278-5784-cc6a-7026-2ffd3573ca67', N'JOBS', N'JOB-301', N'طبيب', NULL, 1, 13, 'dd1b30b2-b42e-5efb-4d82-ac338fee30e7', NULL, NULL, N'{}', NULL),
    ('2a0c88ce-1309-7d13-fbe6-45930dc3e009', N'JOBS', N'JOB-302', N'محامٍ', NULL, 1, 14, 'dd1b30b2-b42e-5efb-4d82-ac338fee30e7', NULL, NULL, N'{}', NULL),
    ('8e1bc699-74bc-a5fe-36e4-7f6727f0eb1f', N'JOBS', N'JOB-303', N'مهندس استشاري', NULL, 1, 15, 'dd1b30b2-b42e-5efb-4d82-ac338fee30e7', NULL, NULL, N'{}', NULL),
    ('22f4e7b1-863c-96c4-439f-d8b67e58abfc', N'JOBS', N'JOB-304', N'صيدلي', NULL, 1, 16, 'dd1b30b2-b42e-5efb-4d82-ac338fee30e7', NULL, NULL, N'{}', NULL),
    ('bc0e14fd-0191-73da-0c6f-95f31a834712', N'JOBS', N'JOB-305', N'محاسب قانوني', NULL, 1, 17, 'dd1b30b2-b42e-5efb-4d82-ac338fee30e7', NULL, NULL, N'{}', NULL),
    ('0312ca10-720a-d593-fc3b-7dff889f4062', N'JOBS', N'JOB-401', N'ضابط شرطة', NULL, 1, 18, 'd7dc0765-809d-b249-d14d-32856bba3c8a', NULL, NULL, N'{}', NULL),
    ('8ba1be10-0069-f20d-def3-ab75942db71c', N'JOBS', N'JOB-402', N'ضابط قوات مسلحة', NULL, 1, 19, 'd7dc0765-809d-b249-d14d-32856bba3c8a', NULL, NULL, N'{}', NULL),
    ('40bdbbed-df21-9114-77b2-3b490a282c30', N'JOBS', N'JOB-403', N'ضابط مخابرات', NULL, 1, 20, 'd7dc0765-809d-b249-d14d-32856bba3c8a', NULL, NULL, N'{}', NULL),
    ('e24ac37b-2872-a645-3d23-c5d470a2ae69', N'JOBS', N'JOB-404', N'ضابط حرس حدود', NULL, 1, 21, 'd7dc0765-809d-b249-d14d-32856bba3c8a', NULL, NULL, N'{}', NULL),
    ('0209d13b-5d70-a63a-ce56-07d25e0095f7', N'JOBS', N'JOB-501', N'ربة منزل', NULL, 1, 22, NULL, NULL, NULL, N'{}', NULL),
    ('76dd6eee-63b1-b580-4942-4b360acf1204', N'JOBS', N'JOB-502', N'متقاعد', NULL, 1, 23, NULL, NULL, NULL, N'{}', NULL),
    ('f676a6a7-a269-7a1f-06e7-ac58956dcb7f', N'JOBS', N'JOB-503', N'لا يعمل', NULL, 1, 24, NULL, NULL, NULL, N'{}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- QUALIFICATIONS (14 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('67eaf43b-1341-a641-9777-d1be50121df6', N'QUALIFICATIONS', N'QUA-01', N'ثانوية عامة', NULL, 1, 0, NULL, NULL, NULL, N'{"level":"ثانوي","track":"عام"}', NULL),
    ('30a58de9-2c60-77b6-d542-e85985151614', N'QUALIFICATIONS', N'QUA-02', N'الثانوية الأزهرية', NULL, 1, 1, NULL, NULL, NULL, N'{"level":"ثانوي","track":"أزهري"}', NULL),
    ('2f10d406-2c8c-14f6-85f4-5679333311b0', N'QUALIFICATIONS', N'QUA-03', N'شهادة وافد', NULL, 1, 2, NULL, NULL, NULL, N'{"level":"ثانوي","track":"وافد"}', NULL),
    ('320e59aa-6802-bd8c-902d-d4980d286247', N'QUALIFICATIONS', N'QUA-04', N'IG', NULL, 1, 3, NULL, NULL, NULL, N'{"level":"ثانوي","track":"أجنبي"}', NULL),
    ('bc43de42-f0a5-9eaf-c394-8db5fc1e9a87', N'QUALIFICATIONS', N'QUA-05', N'الدبلوم الأمريكي', NULL, 1, 4, NULL, NULL, NULL, N'{"level":"ثانوي","track":"أجنبي"}', NULL),
    ('f75d18e1-8194-48d9-ef3a-e1ddd6b89bcd', N'QUALIFICATIONS', N'QUA-06', N'الباكلوريا الفرنسية', NULL, 1, 5, NULL, NULL, NULL, N'{"level":"ثانوي","track":"أجنبي"}', NULL),
    ('7925f7e1-a961-ae86-7f01-dd58c74fbc48', N'QUALIFICATIONS', N'QUA-07', N'دبلوم فنّي', NULL, 1, 6, NULL, NULL, NULL, N'{"level":"دبلوم","track":"عام"}', NULL),
    ('68ada528-999c-8431-a5d5-a6deabdcfa55', N'QUALIFICATIONS', N'QUA-08', N'بكالوريوس الحقوق', NULL, 1, 7, NULL, NULL, NULL, N'{"level":"بكالوريوس","track":"حقوق"}', NULL),
    ('105061d8-e216-14ca-2333-e68bda50236f', N'QUALIFICATIONS', N'QUA-09', N'بكالوريوس تجارة', NULL, 1, 8, NULL, NULL, NULL, N'{"level":"بكالوريوس","track":"عام"}', NULL),
    ('c214ea95-be40-58b6-a611-d12c35c12861', N'QUALIFICATIONS', N'QUA-10', N'بكالوريوس هندسة', NULL, 1, 9, NULL, NULL, NULL, N'{"level":"بكالوريوس","track":"عام"}', NULL),
    ('e5e9a6cd-df72-6311-48b0-30e690ea5a09', N'QUALIFICATIONS', N'QUA-11', N'بكالوريوس تربية رياضية', NULL, 1, 10, NULL, NULL, NULL, N'{"level":"بكالوريوس","track":"خاص"}', NULL),
    ('f6ea6fb2-33a2-7a8a-89bf-0ee35307d24c', N'QUALIFICATIONS', N'QUA-12', N'دبلوم عالٍ', NULL, 1, 11, NULL, NULL, NULL, N'{"level":"دبلوم","track":"عام"}', NULL),
    ('429ef789-03c4-9586-6551-c3fcd50aa5e7', N'QUALIFICATIONS', N'QUA-13', N'ماجستير', NULL, 1, 12, NULL, NULL, NULL, N'{"level":"ماجستير","track":"عام"}', NULL),
    ('cb24fc9d-1417-f3fe-b576-fc66326aa57f', N'QUALIFICATIONS', N'QUA-14', N'دكتوراه', NULL, 1, 13, NULL, NULL, NULL, N'{"level":"دكتوراه","track":"عام"}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- ANNOUNCEMENTS (4 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('0dab92e0-b0af-807e-5f79-53099f1b0290', N'ANNOUNCEMENTS', N'ANN-01', N'فتح باب التقديم لدورة 2026', NULL, 1, 0, NULL, NULL, NULL, N'{"categoryCode":null,"gender":"any","divisionCode":null,"publishAt":"2026-05-01T08:00:00.000Z","expireAt":"2026-07-31T23:59:00.000Z","body":"تعلن أكاديمية الشرطة عن فتح باب التقديم لدورة 2026 لجميع الفئات. آخر موعد للتقديم: 31 يوليو 2026."}', NULL),
    ('c3f288ef-a7a5-cc38-cf2a-398839f3884e', N'ANNOUNCEMENTS', N'ANN-02', N'مواعيد اختبارات الذكور — علمي', NULL, 1, 1, NULL, NULL, NULL, N'{"categoryCode":"CAT-01","gender":"male","divisionCode":"DIV-01","publishAt":"2026-06-01T08:00:00.000Z","expireAt":"2026-06-30T23:59:00.000Z","body":"تبدأ اختبارات المتقدمين الذكور من شعبة علمي علوم يوم الأحد 14 يونيو 2026."}', NULL),
    ('13cf5dd1-523b-f4bd-f025-793692482baa', N'ANNOUNCEMENTS', N'ANN-03', N'مواعيد اختبارات الإناث', NULL, 1, 2, NULL, NULL, NULL, N'{"categoryCode":"CAT-02","gender":"female","divisionCode":null,"publishAt":"2026-06-01T08:00:00.000Z","expireAt":"2026-06-30T23:59:00.000Z","body":"تبدأ اختبارات المتقدمات يوم الاثنين 15 يونيو 2026."}', NULL),
    ('0bb552d3-10fe-9d91-f9fb-ab6a99ae9728', N'ANNOUNCEMENTS', N'ANN-04', N'متطلبات الأزهر الشريف', NULL, 1, 3, NULL, NULL, NULL, N'{"categoryCode":"CAT-03","gender":"any","divisionCode":null,"publishAt":"2026-05-15T08:00:00.000Z","expireAt":null,"body":"على متقدمي الأزهر الشريف إحضار شهادة المعادلة الأزهرية الأصلية + 4 صور شخصية."}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- APPLICANT_DIVISIONS (5 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('650b6d7e-55bf-1a0e-bcd0-c64581980e95', N'APPLICANT_DIVISIONS', N'DIV-01', N'علمي علوم', NULL, 1, 0, NULL, NULL, NULL, N'{}', NULL),
    ('97de5ac8-6cac-80d2-139c-6caf85f9311a', N'APPLICANT_DIVISIONS', N'DIV-02', N'علمي رياضة', NULL, 1, 1, NULL, NULL, NULL, N'{}', NULL),
    ('1ff811cc-ea28-6e2e-773c-ef541ada8f4b', N'APPLICANT_DIVISIONS', N'DIV-03', N'أدبي', NULL, 1, 2, NULL, NULL, NULL, N'{}', NULL),
    ('dacb464d-8af3-c78e-b52d-f0330041abac', N'APPLICANT_DIVISIONS', N'DIV-04', N'أزهري علمي', NULL, 1, 3, NULL, NULL, NULL, N'{}', NULL),
    ('0a8c46eb-0379-8396-cece-7c73d73becdb', N'APPLICANT_DIVISIONS', N'DIV-05', N'أزهري أدبي', NULL, 1, 4, NULL, NULL, NULL, N'{}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- SCHOOL_CATEGORIES (6 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('caddd227-43ef-2d2d-f729-eb201b7a5791', N'SCHOOL_CATEGORIES', N'SCH-01', N'حكومي', NULL, 1, 0, NULL, NULL, NULL, N'{}', NULL),
    ('4b779ac2-cf03-ef10-2271-e6de533f42ec', N'SCHOOL_CATEGORIES', N'SCH-02', N'خاص', NULL, 1, 1, NULL, NULL, NULL, N'{}', NULL),
    ('cc76c5b4-b5dd-467d-e6af-6f450986e5a6', N'SCHOOL_CATEGORIES', N'SCH-03', N'تجريبي', NULL, 1, 2, NULL, NULL, NULL, N'{}', NULL),
    ('b2ecf0d0-58d5-f82e-c8e7-462344d3feb2', N'SCHOOL_CATEGORIES', N'SCH-04', N'لغات', NULL, 1, 3, NULL, NULL, NULL, N'{}', NULL),
    ('b6a5ef4f-91b6-c4f7-506e-22aa52110e70', N'SCHOOL_CATEGORIES', N'SCH-05', N'أزهري', NULL, 1, 4, NULL, NULL, NULL, N'{}', NULL),
    ('f50b41f2-811b-3bd4-c459-2d840bf34046', N'SCHOOL_CATEGORIES', N'SCH-06', N'دولي', NULL, 1, 5, NULL, NULL, NULL, N'{}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

-- NID_MISSING_REASONS (6 rows)
MERGE INTO dbo.lookup_items AS tgt
USING (VALUES
    ('b562fb1f-bced-122b-a25e-e49637cd23b7', N'NID_MISSING_REASONS', N'NMR-01', N'لم يبلغ سن استخراج البطاقة', NULL, 1, 0, NULL, NULL, NULL, N'{"requiresUpload":true}', NULL),
    ('b1a71056-01e1-b1d1-dc47-225998e07245', N'NID_MISSING_REASONS', N'NMR-02', N'البطاقة قيد الإصدار', NULL, 1, 1, NULL, NULL, NULL, N'{"requiresUpload":true}', NULL),
    ('894020e4-bed2-370a-7e6b-375ce2e43b11', N'NID_MISSING_REASONS', N'NMR-03', N'البطاقة مفقودة', NULL, 1, 2, NULL, NULL, NULL, N'{"requiresUpload":true}', NULL),
    ('18091da9-ce76-5416-9e88-198b3f30db0b', N'NID_MISSING_REASONS', N'NMR-04', N'البطاقة تالفة', NULL, 1, 3, NULL, NULL, NULL, N'{"requiresUpload":true}', NULL),
    ('6df2e6d4-4ef0-b748-1eca-e7b68be6d6bf', N'NID_MISSING_REASONS', N'NMR-05', N'غير مصري الجنسية', NULL, 1, 4, NULL, NULL, NULL, N'{"requiresUpload":false}', NULL),
    ('58956a1e-fd04-5751-2c2d-6041f2d8a79f', N'NID_MISSING_REASONS', N'NMR-06', N'أخرى', NULL, 1, 5, NULL, NULL, NULL, N'{"requiresUpload":true}', NULL)
) AS src(id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id, start_date, end_date, extras, faculty_code)
ON tgt.lookup_type_code = src.lookup_type_code AND tgt.code = src.code AND tgt.deleted_at IS NULL
WHEN NOT MATCHED THEN
  INSERT (id, lookup_type_code, code, name_ar, name_en, is_active, sort_order, parent_id,
          start_date, end_date, extras, faculty_code, created_at, created_by, updated_at, updated_by)
  VALUES (src.id, src.lookup_type_code, src.code, src.name_ar, src.name_en, src.is_active, src.sort_order,
          src.parent_id, src.start_date, src.end_date, src.extras, src.faculty_code,
          SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001', SYSUTCDATETIME(), '00000000-0000-0000-0000-000000000001');

COMMIT;
PRINT 'Lookup catalogue seed applied — 296 rows merged.';
