// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PACademy.Admin.Api.Persistence;

#nullable disable

namespace PACademy.Admin.Api.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260530114800_AddGeneralSettingsTable")]
    partial class AddGeneralSettingsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PACademy_staging_db")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PACademy.Admin.Api.Modules.AdminRecords.AdminRecordDocumentEntity", b =>
                {
                    b.Property<string>("Module")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("module");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Module", "Id");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_admin_record_documents_module");

                    b.ToTable("admin_record_documents", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.AdminRecords.AdminRecordEntity", b =>
                {
                    b.Property<string>("Module")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("module");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Module", "Id");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_admin_records_module");

                    b.ToTable("admin_records", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Admissions.AdmissionCycleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_admission_cycles_is_active");

                    b.ToTable("admission_cycles", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Admissions.AdmissionRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CycleId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("cycle_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_admission_rules_cycle_version");

                    b.ToTable("admission_rules", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Admissions.ApplicantCategoryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit")
                        .HasColumnName("is_open");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("label_ar");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Key");

                    b.ToTable("applicant_categories", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Admissions.ApplicationSettingsCategoryConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_app_settings_configs_category_id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_app_settings_configs_sort_order");

                    b.ToTable("application_settings_category_configs", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Admissions.ApplicationSettingsCategorySpecializationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("config_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SpecializationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("specialization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId")
                        .HasDatabaseName("ix_app_settings_specs_config_id");

                    b.HasIndex("ConfigId", "SpecializationId")
                        .IsUnique()
                        .HasDatabaseName("ux_app_settings_specs_config_specialization");

                    b.ToTable("application_settings_category_specializations", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Admissions.ApplicationSettingsGraduationYearEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("id");

                    b.Property<string>("AcademicGradeId")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("academic_grade_id");

                    b.Property<int?>("AgeMin")
                        .HasColumnType("int")
                        .HasColumnName("age_min");

                    b.Property<DateOnly>("AgeReferenceDate")
                        .HasColumnType("date")
                        .HasColumnName("age_reference_date");

                    b.Property<DateOnly>("ApplicationEndDate")
                        .HasColumnType("date")
                        .HasColumnName("application_end_date");

                    b.Property<DateOnly>("ApplicationStartDate")
                        .HasColumnType("date")
                        .HasColumnName("application_start_date");

                    b.Property<string>("CategorySpecializationId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("category_specialization_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DivisionCodesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("division_codes_json");

                    b.Property<string>("GenderTypesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender_types_json");

                    b.Property<string>("GradeKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("grade_kind");

                    b.Property<string>("GraduationYearsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("graduation_years_json");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("MaritalStatusCodesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marital_status_codes_json");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int")
                        .HasColumnName("max_age");

                    b.Property<decimal?>("MinPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("min_percentage");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SchoolCategoryCodesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("school_category_codes_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategorySpecializationId")
                        .HasDatabaseName("ix_app_settings_years_category_specialization_id");

                    b.HasIndex("CategorySpecializationId", "ApplicationStartDate", "ApplicationEndDate")
                        .HasDatabaseName("ix_app_settings_years_window");

                    b.ToTable("application_settings_graduation_years", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Audit.AuditRowEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("entity");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("module");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("audit_entries", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamAssignmentEntity", b =>
                {
                    b.Property<string>("ExamId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("exam_id");

                    b.Property<string>("AssignmentKind")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("assignment_kind");

                    b.Property<int>("AssignmentOrder")
                        .HasColumnType("int")
                        .HasColumnName("assignment_order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("value");

                    b.HasKey("ExamId", "AssignmentKind", "AssignmentOrder");

                    b.ToTable("exam_assignments", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("id");

                    b.Property<string>("AccessEndAt")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("access_end_at");

                    b.Property<string>("AccessStartAt")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("access_start_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CycleId")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("cycle_id");

                    b.Property<string>("CycleName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("cycle_name");

                    b.Property<string>("DisplayMode")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("display_mode");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name_ar");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("int")
                        .HasColumnName("question_count");

                    b.Property<bool?>("RandomQuestionOrder")
                        .HasColumnType("bit")
                        .HasColumnName("random_question_order");

                    b.Property<bool?>("RandomSelection")
                        .HasColumnType("bit")
                        .HasColumnName("random_selection");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("ScheduledFor")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("scheduled_for");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("ix_exams_cycle_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_exams_status");

                    b.ToTable("exams", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("category");

                    b.Property<string>("Classification")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("classification");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("int")
                        .HasColumnName("correct_index");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int")
                        .HasColumnName("difficulty");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("image_url");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("int")
                        .HasColumnName("time_limit_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_exam_questions_category");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_exam_questions_status");

                    b.ToTable("exam_questions", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionLinkEntity", b =>
                {
                    b.Property<string>("ExamId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("exam_id");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("int")
                        .HasColumnName("question_order");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("question_id");

                    b.HasKey("ExamId", "QuestionOrder");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_exam_question_links_question_id");

                    b.ToTable("exam_question_links", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionMatchingPairEntity", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("question_id");

                    b.Property<int>("PairOrder")
                        .HasColumnType("int")
                        .HasColumnName("pair_order");

                    b.Property<string>("MatchText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("match_text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prompt");

                    b.HasKey("QuestionId", "PairOrder");

                    b.ToTable("exam_question_matching_pairs", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionOptionEntity", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("question_id");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int")
                        .HasColumnName("option_order");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option_text");

                    b.HasKey("QuestionId", "OptionOrder");

                    b.ToTable("exam_question_options", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamRuleEntity", b =>
                {
                    b.Property<string>("ExamId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("exam_id");

                    b.Property<int>("RuleOrder")
                        .HasColumnType("int")
                        .HasColumnName("rule_order");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("category");

                    b.Property<int>("DifficultyMax")
                        .HasColumnType("int")
                        .HasColumnName("difficulty_max");

                    b.Property<int>("DifficultyMin")
                        .HasColumnType("int")
                        .HasColumnName("difficulty_min");

                    b.Property<int>("Minutes")
                        .HasColumnType("int")
                        .HasColumnName("minutes");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int")
                        .HasColumnName("question_count");

                    b.HasKey("ExamId", "RuleOrder");

                    b.ToTable("exam_rules", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Identity.OfficerEntity", b =>
                {
                    b.Property<string>("NationalId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("national_id");

                    b.Property<string>("FullArabicName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_arabic_name");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("OfficerCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("officer_code");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("user_type");

                    b.HasKey("NationalId");

                    b.ToTable("officer_directory", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Identity.RoleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("key");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("label_ar");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_key");

                    b.ToTable("roles", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Identity.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("account_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("FullArabicName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("full_arabic_name");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("national_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_national_id");

                    b.ToTable("users", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Lookups.LookupRowEntity", b =>
                {
                    b.Property<string>("LookupKey")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("lookup_key");

                    b.Property<string>("Code")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("LookupKey", "Code");

                    b.HasIndex("LookupKey")
                        .HasDatabaseName("ix_lookup_rows_lookup_key");

                    b.ToTable("lookup_rows", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Settings.GeneralSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<string>("AcquaintanceDocumentsEntryResponsibleTestCode")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("acquaintance_documents_entry_responsible_test_code");

                    b.Property<string>("AcquaintanceDocumentsMutationLockTiming")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)")
                        .HasColumnName("acquaintance_documents_mutation_lock_timing");

                    b.Property<string>("AcquaintanceDocumentsPrintResponsibleTestCode")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("acquaintance_documents_print_responsible_test_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("ExamDaysPerApplicant")
                        .HasColumnType("int")
                        .HasColumnName("exam_days_per_applicant");

                    b.Property<int>("ExamSlotSelectionWindowDays")
                        .HasColumnType("int")
                        .HasColumnName("exam_slot_selection_window_days");

                    b.Property<string>("PrimaryRelativesEntryResponsibleTestCode")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("primary_relatives_entry_responsible_test_code");

                    b.Property<string>("PrimaryRelativesVisibilityResponsibleTestCode")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)")
                        .HasColumnName("primary_relatives_visibility_responsible_test_code");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("general_settings", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Persistence.ApplicantPortalRecordEntity", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("type");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("record_id");

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("applicant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Type", "RecordId");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("ix_portal_records_applicant_id");

                    b.ToTable("applicant_portal_records", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Persistence.ExamSlotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("location");

                    b.Property<int>("Reserved")
                        .HasColumnType("int")
                        .HasColumnName("reserved");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_exam_slots_date");

                    b.ToTable("exam_slots", "PACademy_staging_db");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamAssignmentEntity", b =>
                {
                    b.HasOne("PACademy.Admin.Api.Modules.Exams.ExamEntity", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionLinkEntity", b =>
                {
                    b.HasOne("PACademy.Admin.Api.Modules.Exams.ExamEntity", null)
                        .WithMany("QuestionLinks")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionMatchingPairEntity", b =>
                {
                    b.HasOne("PACademy.Admin.Api.Modules.Exams.ExamQuestionEntity", null)
                        .WithMany("MatchingPairs")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionOptionEntity", b =>
                {
                    b.HasOne("PACademy.Admin.Api.Modules.Exams.ExamQuestionEntity", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamRuleEntity", b =>
                {
                    b.HasOne("PACademy.Admin.Api.Modules.Exams.ExamEntity", null)
                        .WithMany("Rules")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("QuestionLinks");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("PACademy.Admin.Api.Modules.Exams.ExamQuestionEntity", b =>
                {
                    b.Navigation("MatchingPairs");

                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
